### ISSUE TITLE
Sentry components upgrade fails for snuba: 20.6.0 -> 20.7.2

### ISSUE THREAD

**Issue by chhetripradeep** [getsentry/snuba#1196]
Hi,

I tried upgrading each component of my sentry setup (sentry, snuba and relay) from 20.6.0 to 20.7.2. As far as I know in this release (20.7.2), relay is now a mandatory component and events are ingested into kafka directly from relay. After upgrading, i noticed that snuba-consumer started failing with this stacktrace:

```
2020-08-02 16:21:17,992 New partitions assigned: {Partition(topic=Topic(name='sentry.staging.events'), index=0): 1}
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/consumer.py", line 146, in consumer
    consumer.run()
  File "/usr/src/snuba/snuba/utils/streams/batching.py", line 285, in run
    self._run_once()
  File "/usr/src/snuba/snuba/utils/streams/batching.py", line 296, in _run_once
    self.__processor.process(msg)
  File "/usr/src/snuba/snuba/utils/streams/batching.py", line 139, in process
    result = self.__worker.process_message(message)
  File "/usr/src/snuba/snuba/consumer.py", line 60, in process_message
    rapidjson.loads(message.payload.value),
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x87 in position 0: invalid start byte
```

On looking at the kafka message for events topic, i found the message weird with some non-unicode character: 
https://pastebin.com/raw/iwhMW3Jd

Logs on relay side looks like this: 

```
2020-08-02T16:02:36Z [relay_server::actors::project] DEBUG: project 2 initialized without state
2020-08-02T16:02:36Z [relay_server::actors::project] DEBUG: project 2 state requested
2020-08-02T16:02:36Z [relay_server::actors::project] DEBUG: project 2 state request amended
2020-08-02T16:02:36Z [relay_server::actors::project_upstream] DEBUG: updating project states for 1/1 projects (attempt 1)
2020-08-02T16:02:36Z [relay_server::actors::project_upstream] DEBUG: sending request of size 1
2020-08-02T16:02:36Z [relay_server::actors::project] DEBUG: project 2 state updated
2020-08-02T16:11:15Z [relay_server::actors::project] DEBUG: project 2 state requested
2020-08-02T16:11:15Z [relay_server::actors::project] DEBUG: project 2 state request amended
2020-08-02T16:11:15Z [relay_server::actors::project_upstream] DEBUG: updating project states for 1/1 projects (attempt 1)
2020-08-02T16:11:15Z [relay_server::actors::project_upstream] DEBUG: sending request of size 1
2020-08-02T16:11:15Z [relay_server::actors::project] DEBUG: project 2 state updated
```

I am not sure what am i missing. Thank you for the help in advance.

**Comment by chhetripradeep** [comment]
Looks like this is the code which is producing those kafka messages: https://github.com/getsentry/relay/blob/master/relay-server/src/actors/store.rs#L461-L476

**Comment by fpacifici** [comment]
Hi, yes that message is definitively not going to work, though Relay does not produce directly to Snuba. It produces on the `ingest` topic. Then Sentry consumes from that topic, it does some work, it produces again on the `events` topic and Snuba consumes from there.
Did you pick the payload in  https://pastebin.com/raw/iwhMW3Jd from the `ingest` topic or from the `events` topic` ? The error message in the stack trace does not seem to correspond with the content of the message in the pastebin.
If you picked it from the `ingest` topic, could you please see what you have on the partition:1 of the `events` topic ?

Thanks

**Comment by chhetripradeep** [comment]
Hi @fpacifici 

Thank you for the quick response. I totally missed the `sentry-ingest-consumer` and thought relay alone is the only new component. I will fix it. Thank you once again for the help.

Regards.
