### ISSUE TITLE
Migration from sentry_local -> errors_local seems to have not taken place

### ISSUE THREAD

**Issue by rma-stripe** [getsentry/snuba#1596]
Hi folks,

We run Sentry 10 internally, but do not use the "onpremise" setup as we want to split out the containers for use with Kubernetes orchestration/separate hosts. In our current install we are running the 20.12.1 release for both Sentry and Snuba, although these have been upgraded from an older version from months ago.

In https://github.com/getsentry/snuba/pull/1354 it appears we migrate events in Clickhouse to live in the `errors_local` table, and this migration seems to have a side-effect of fixing a bug that forced retention to 30d (https://github.com/getsentry/onpremise/issues/612).

However, even after applying Snuba migrations such that the migration above was applied:

```
I have no name!@qa-snubabox--000346c809ef45482:/usr/src/snuba$ /pay/snuba/stripe-snuba-entrypoint.sh snuba bootstrap --force
2021-01-13 00:22:14,466 Failed to create topic events
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/cli/bootstrap.py", line 91, in bootstrap
    future.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
cimpl.KafkaException: KafkaError{code=TOPIC_ALREADY_EXISTS,val=36,str="Topic 'events' already exists."}
2021-01-13 00:22:14,467 Failed to create topic errors-replacements
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/cli/bootstrap.py", line 91, in bootstrap
    future.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
cimpl.KafkaException: KafkaError{code=TOPIC_ALREADY_EXISTS,val=36,str="Topic 'errors-replacements' already exists."}
2021-01-13 00:22:14,467 Failed to create topic cdc
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/cli/bootstrap.py", line 91, in bootstrap
    future.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
cimpl.KafkaException: KafkaError{code=TOPIC_ALREADY_EXISTS,val=36,str="Topic 'cdc' already exists."}
2021-01-13 00:22:14,467 Failed to create topic outcomes
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/cli/bootstrap.py", line 91, in bootstrap
    future.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
cimpl.KafkaException: KafkaError{code=TOPIC_ALREADY_EXISTS,val=36,str="Topic 'outcomes' already exists."}
2021-01-13 00:22:14,467 Failed to create topic ingest-sessions
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/cli/bootstrap.py", line 91, in bootstrap
    future.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
cimpl.KafkaException: KafkaError{code=TOPIC_ALREADY_EXISTS,val=36,str="Topic 'ingest-sessions' already exists."}
2021-01-13 00:22:14,468 Failed to create topic event-replacements
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/cli/bootstrap.py", line 91, in bootstrap
    future.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
cimpl.KafkaException: KafkaError{code=TOPIC_ALREADY_EXISTS,val=36,str="Topic 'event-replacements' already exists."}
2021-01-13 00:22:14,468 Failed to create topic snuba-commit-log
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/cli/bootstrap.py", line 91, in bootstrap
    future.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
cimpl.KafkaException: KafkaError{code=TOPIC_ALREADY_EXISTS,val=36,str="Topic 'snuba-commit-log' already exists."}
2021-01-13 00:22:14,492 Running migration: 0012_errors_make_level_nullable
2021-01-13 00:22:14,511 Finished: 0012_errors_make_level_nullable
2021-01-13 00:22:14,520 Running migration: 0009_transactions_fix_title_and_message
2021-01-13 00:22:14,543 Finished: 0009_transactions_fix_title_and_message
2021-01-13 00:22:14,552 Running migration: 0002_discover_add_deleted_tags_hash_map
2021-01-13 00:22:14,570 Finished: 0002_discover_add_deleted_tags_hash_map
2021-01-13 00:22:14,579 Running migration: 0003_discover_fix_user_column
2021-01-13 00:22:14,592 Finished: 0003_discover_fix_user_column
2021-01-13 00:22:14,601 Running migration: 0004_discover_fix_title_and_message
2021-01-13 00:22:14,619 Finished: 0004_discover_fix_title_and_message
2021-01-13 00:22:14,628 Running migration: 0002_sessions_aggregates
2021-01-13 00:22:14,692 Finished: 0002_sessions_aggregates
```

Events still seem to live in the `sentry_local` table, although `errors_local` does exist:

```
qa-clickhousebox--09bfa9ed07cedab60.northwest.stripe.io :) select count(*) from errors_local

SELECT count(*)
FROM errors_local

┌─count()─┐
│       0 │
└─────────┘

1 rows in set. Elapsed: 0.002 sec.

qa-clickhousebox--09bfa9ed07cedab60.northwest.stripe.io :) select count(*) from sentry_local

SELECT count(*)
FROM sentry_local

┌─count()─┐
│ 4911118 │
└─────────┘

1 rows in set. Elapsed: 0.001 sec.
```

When we run Snuba's cleanup task with `DEFAULT_RETENTION_DAYS = 1` we get a log event back saying that zero partitions have been dropped.

Are we missing something w.r.t. running Snuba migrations, or is there a bug in the code somewhere? The output of `snuba migrations list` appears to signal that migration 0011_rebuild_errors was applied out successfully:

```
events
[X]  0001_events_initial
[X]  0002_events_onpremise_compatibility
[X]  0003_errors
[X]  0004_errors_onpremise_compatibility
[X]  0005_events_tags_hash_map
[X]  0006_errors_tags_hash_map
[X]  0007_groupedmessages
[X]  0008_groupassignees
[X]  0009_errors_add_http_fields
[X]  0010_groupedmessages_onpremise_compatibility
[X]  0011_rebuild_errors
[X]  0012_errors_make_level_nullable
```

Thank you!

**Comment by fpacifici** [comment]
Hi,
you are not missing anything. We are still working on the migrations to the new table. It is normal that your events still live in `sentry_local`. The migration you mentioned `rebuild_errors` was rebuilding the errors table in order to make some DDL changes that cannot be done with an ALTER statement. But we did not yet merge the migration that will transfer data from one table to the other.

**Comment by rma-stripe** [comment]
Got it, we'll be on the lookout for a future release that actually transfers data. Thanks for the speedy response!
