### ISSUE TITLE
snuba 21.1.0 fails to run: ImportError: cannot import name 'PickleBuffer' from 'pickle'

### ISSUE THREAD

**Issue by drook** [getsentry/snuba#1613]
**Env:**
Self-hosted sentry, built from sources.
Snuba: 21.1.0
Python 3.7.7 (default, Jun  7 2020, 08:15:55)

Newly installed snuba fails to run (btw why does the egg always have version 0.0.0 ?):

````
Jan 24 10:06:05 sentry snuba[18690]: ImportError: cannot import name 'PickleBuffer' from 'pickle' (/usr/local/lib/python3.7/pickle.py)
Jan 24 10:06:05 sentry snuba[18684]: Traceback (most recent call last):
Jan 24 10:06:05 sentry snuba[18684]:   File "/usr/local/bin/snuba", line 11, in <module>
Jan 24 10:06:05 sentry snuba[18684]:     load_entry_point('snuba==0.0.0', 'console_scripts', 'snuba')()
Jan 24 10:06:05 sentry snuba[18684]:   File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
Jan 24 10:06:05 sentry snuba[18684]:     return get_distribution(dist).load_entry_point(group, name)
Jan 24 10:06:05 sentry snuba[18684]:   File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
Jan 24 10:06:05 sentry snuba[18684]:     return ep.load()
Jan 24 10:06:05 sentry snuba[18684]:   File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
Jan 24 10:06:05 sentry snuba[18684]:     return self.resolve()
Jan 24 10:06:05 sentry snuba[18684]:   File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
Jan 24 10:06:05 sentry snuba[18684]:     module = __import__(self.module_name, fromlist=['__name__'], level=0)
Jan 24 10:06:05 sentry snuba[18684]:   File "/usr/local/lib/python3.7/site-packages/snuba-0.0.0-py3.7.egg/snuba/cli/__init__.py", line 21, in <module>
Jan 24 10:06:05 sentry snuba[18684]:     module = __import__(module_name, globals(), locals(), ["__name__"])
Jan 24 10:06:05 sentry snuba[18684]:   File "/usr/local/lib/python3.7/site-packages/snuba-0.0.0-py3.7.egg/snuba/cli/bootstrap.py", line 6, in <module>
Jan 24 10:06:05 sentry snuba[18684]:     from snuba.datasets.factory import ACTIVE_DATASET_NAMES, get_dataset
Jan 24 10:06:05 sentry snuba[18684]:   File "/usr/local/lib/python3.7/site-packages/snuba-0.0.0-py3.7.egg/snuba/datasets/factory.py", line 4, in <module>
Jan 24 10:06:05 sentry snuba[18684]:     from snuba.datasets.dataset import Dataset
Jan 24 10:06:05 sentry snuba[18684]:   File "/usr/local/lib/python3.7/site-packages/snuba-0.0.0-py3.7.egg/snuba/datasets/dataset.py", line 6, in <module>
Jan 24 10:06:05 sentry snuba[18684]:     from snuba.datasets.entities.factory import get_entity
Jan 24 10:06:05 sentry snuba[18684]:   File "/usr/local/lib/python3.7/site-packages/snuba-0.0.0-py3.7.egg/snuba/datasets/entities/factory.py", line 4, in <module>
Jan 24 10:06:05 sentry snuba[18684]:     from snuba.datasets.entity import Entity
Jan 24 10:06:05 sentry snuba[18684]:   File "/usr/local/lib/python3.7/site-packages/snuba-0.0.0-py3.7.egg/snuba/datasets/entity.py", line 5, in <module>
Jan 24 10:06:05 sentry snuba[18684]:     from snuba.datasets.plans.query_plan import ClickhouseQueryPlan
Jan 24 10:06:05 sentry snuba[18684]:   File "/usr/local/lib/python3.7/site-packages/snuba-0.0.0-py3.7.egg/snuba/datasets/plans/query_plan.py", line 7, in <module>
Jan 24 10:06:05 sentry snuba[18684]:     from snuba.clickhouse.processors import QueryProcessor
Jan 24 10:06:05 sentry snuba[18684]:   File "/usr/local/lib/python3.7/site-packages/snuba-0.0.0-py3.7.egg/snuba/clickhouse/processors.py", line 6, in <module>
Jan 24 10:06:05 sentry snuba[18684]:     from snuba.request.request_settings import RequestSettings
Jan 24 10:06:05 sentry snuba[18684]:   File "/usr/local/lib/python3.7/site-packages/snuba-0.0.0-py3.7.egg/snuba/request/__init__.py", line 12, in <module>
Jan 24 10:06:05 sentry snuba[18684]:     from snuba.request.request_settings import RequestSettings
Jan 24 10:06:05 sentry snuba[18684]:   File "/usr/local/lib/python3.7/site-packages/snuba-0.0.0-py3.7.egg/snuba/request/request_settings.py", line 5, in <module>
Jan 24 10:06:05 sentry snuba[18684]:     from snuba.state.rate_limit import get_global_rate_limit_params, RateLimitParameters
Jan 24 10:06:05 sentry snuba[18684]:   File "/usr/local/lib/python3.7/site-packages/snuba-0.0.0-py3.7.egg/snuba/state/__init__.py", line 18, in <module>
Jan 24 10:06:05 sentry snuba[18684]:     from snuba.utils.streams.backends.kafka import (
Jan 24 10:06:05 sentry snuba[18684]:   File "/usr/local/lib/python3.7/site-packages/snuba-0.0.0-py3.7.egg/snuba/utils/streams/backends/kafka.py", line 9, in <module>
Jan 24 10:06:05 sentry snuba[18684]:     from pickle import PickleBuffer
Jan 24 10:06:05 sentry snuba[18684]: ImportError: cannot import name 'PickleBuffer' from 'pickle' (/usr/local/lib/python3.7/pickle.py)
````

**Comment by drook** [comment]
Exactly same story with 20.12.1 release. Rolled back the 20.8.0.

**Comment by drook** [comment]
Tried to install pickle5 python-wide using pip - this doesn't help. I'm out of ideas atm.

**Comment by drook** [comment]
My bad, looks like snuba >= 20.10.x needs python 3.9, not 3.7.
