### ISSUE TITLE
Permission denied when snuba consumer tries to write data when running containers as non-root

### ISSUE THREAD

**Issue by cjesper** [getsentry/snuba#2407]
### Environment
Sentry: Running onpremise, version 20.3.9.70. On Ubuntu 20.04.

Which SDK and version?
Not applicable

### Steps to Reproduce
I want the sentry docker containers to run as a non-root user. I've created a specific sentry OS user for this purpose. I've made the sentry user the owner of both the source code (the onpremise/master-directory downloaded from git) and of the /volumes directory. I then run the docker-compose up command as this sentry user.
However, the snuba-consumer and snuba-outcomes-consumer containers refuse to start due to getting a permission denied error:
`snuba.clickhouse.errors.ClickhouseWriterError: Could not calculate available disk space (statvfs), errno: 13, strerror: Permission denied (version 20.3.9.70 (official build))`

Full stacktrace:
`2022-02-14 08:47:37,064 New partitions assigned: {Partition(topic=Topic(name='events'), index=0): 4903313}
2022-02-14 08:47:38,213 Caught {
  "__type__": "SerializableException",
  "__name__": "ClickhouseWriterError",
  "__message__": "Could not calculate available disk space (statvfs), errno: 13, strerror: Permission denied (version 20.3.9.70 (official build))",
  "__should_report__": true,
  "__extra_data__": {
    "code": 214,
    "row": null
  }
}, shutting down...
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/consumer.py", line 180, in consumer
    consumer.run()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 108, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 143, in _run_once
    self.__processing_strategy.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/streaming/filter.py", line 26, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/streaming/transform.py", line 58, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/streaming/collect.py", line 123, in poll
    self.__close_and_reset_batch()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/streaming/collect.py", line 105, in __close_and_reset_batch
    self.__batch.close()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/streaming/collect.py", line 64, in close
    self.__step.close()
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 250, in close
    self.__insert_batch_writer.close()
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 88, in close
    self.__writer.write(
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 246, in write
    batch.join()
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 194, in join
    raise ClickhouseWriterError(message, code=code, row=row)
snuba.clickhouse.errors.ClickhouseWriterError: Could not calculate available disk space (statvfs), errno: 13, strerror: Permission denied (version 20.3.9.70 (official build))`

**Comment by vladkluev** [comment]
It seems like the user that the clickhouse container is running under cannot make the `statvfs` [syscall](https://man7.org/linux/man-pages/man3/statvfs.3.html). Try doing the following:

1. Open a shell on the container running clickhouse
2. run `df` in that shell. `df` 

My hypothesis is that you will get a permission denied error there as well. Clickhouse needs the ability to read the filesystem information to know if it can write data or do a merge. Once the `df` call works, the write to clickhouse should work as well.

Let me know if my hypothesis was incorrect.
