### ISSUE TITLE
Subscriptions combined scheduler and executor missing `--partitions` option

### ISSUE THREAD

**Issue by z0rc** [getsentry/snuba#2884]
### Environment

How do you use Sentry?
self-hosted 22.6.0

Which SDK and version?
Irrelevant

### Steps to Reproduce

1. Use external kafka with partitioned topics for HA
2. Up until 22.5.0 run `snuba subscription` with `--partitions` argument matching number of kafka partitions. Per https://forum.sentry.io/t/perfomance-metric-alarm-related-to-snuba-events-subscriptions-consumers-snuba-transactions-subscriptions-consumers/15102/2
3. Update to 22.6.0 and switch to `snuba subscriptions-scheduler-executor`

### Expected Result

Things continue to work as expected. 

### Actual Result

`--partitions` option isn't implemented for `subscriptions-scheduler-executor`. Running without `--partitions` options produces:
```
2022-06-24 15:52:08,683 New partitions assigned: {Partition(topic=Topic(name='snuba-commit-log'), index=0): 9934428, Partition(topic=Topic(name='snuba-commit-log'), index=1): 11463552, Partition(topic=Topic(name='snuba-commit-log'), index=2): 1970262, Partition(topic=Topic(name='snuba-commit-log'), index=3): 8502404, Partition(topic=Topic(name='snuba-commit-log'), index=4): 11649, Partition(topic=Topic(name='snuba-commit-log'), index=5): 0, Partition(topic=Topic(name='snuba-commit-log'), index=6): 4482588, Partition(topic=Topic(name='snuba-commit-log'), index=7): 4746035, Partition(topic=Topic(name='snuba-commit-log'), index=8): 1914984, Partition(topic=Topic(name='snuba-commit-log'), index=9): 5896262}
2022-06-24 15:52:10,244 Caught KeyError(7), shutting down...
2022-06-24 15:52:10,244 Closing <snuba.subscriptions.scheduler_consumer.CommitLogTickConsumer object at 0x7efed0a9ca00>...
2022-06-24 15:52:10,244 Partitions revoked: [Partition(topic=Topic(name='snuba-commit-log'), index=0), Partition(topic=Topic(name='snuba-commit-log'), index=1), Partition(topic=Topic(name='snuba-commit-log'), index=2), Partition(topic=Topic(name='snuba-commit-log'), index=3), Partition(topic=Topic(name='snuba-commit-log'), index=4), Partition(topic=Topic(name='snuba-commit-log'), index=5), Partition(topic=Topic(name='snuba-commit-log'), index=6), Partition(topic=Topic(name='snuba-commit-log'), index=7), Partition(topic=Topic(name='snuba-commit-log'), index=8), Partition(topic=Topic(name='snuba-commit-log'), index=9)]
2022-06-24 15:52:10,247 Processor terminated
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/subscriptions_scheduler_executor.py", line 152, in subscriptions_scheduler_executor
    processor.run()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 121, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 159, in _run_once
    self.__processing_strategy.submit(self.__message)
  File "/usr/src/snuba/snuba/subscriptions/scheduler_processing_strategy.py", line 252, in submit
    self.__next_step.submit(message)
  File "/usr/src/snuba/snuba/subscriptions/combined_scheduler_executor.py", line 248, in submit
    tasks.extend([task for task in entity_scheduler[tick.partition].find(tick)])
KeyError: 7
```

**Comment by lynnagara** [comment]
The partitions value should be configured in Snuba via a custom settings file. e.g. `TOPIC_PARTITION_COUNTS = {"events": 3}` if you have 3 partitions. @getsentry/open-source What's the best way to achieve this with the self hosted configuration?

**Comment by chadwhitacre** [comment]
I don't think we have a Snuba config file like we do for [Relay](https://github.com/getsentry/self-hosted/tree/2672ce545227f9a40b90178006c5ab25f7860a64/relay) and [Sentry](https://github.com/getsentry/self-hosted/tree/2672ce545227f9a40b90178006c5ab25f7860a64/sentry). Time to add one, it seems. :)

**Comment by chadwhitacre** [comment]
In the meantime you might be able to use [`enhance-image.sh`](https://develop.sentry.dev/self-hosted/#configuration) but it's probably complicated.

**Comment by z0rc** [comment]
@lynnagara you mention `events` topic, but error log shows `snuba-commit-log`, which is confusing. Can you please elaborate on which topics are used by `subscriptions-scheduler-executor` and require additional configuration via `TOPIC_PARTITION_COUNTS`?

**Comment by lynnagara** [comment]
It is a bit confusing. `events` is the main topic and we write the partitions/offsets of that topic into `snuba-commit-log` to indicate when we're done processing/storing them and can start running subscriptions and other post processing tasks. The commit log topic exists only track progress on the main topic.

Increasing partitions on `events` can help if a single consumer can't keep up with your event volume. But `snuba-commit-log` only ever gets a handful of messages each second regardless of the number of raw messages received and should never have more than one partition.

**Comment by z0rc** [comment]
@souredoutlook maybe. I still miss `--partitions` option from old `subscription` command with new `subscriptions-scheduler-executor`. That would make my live much easier, as configuring `TOPIC_PARTITION_COUNTS` settings option is more complicated and involved.

In ideal world neither of those would be required, if snuba executors can auto determine topic partition count. But just can't nice things.

**Comment by chadwhitacre** [comment]
@lynnagara Is this a reasonable ask, to implement `--partitions` for `subscriptions-scheudler-executor`? If so let's get a ticket made in `snuba` to track.

**Comment by lynnagara** [comment]
It is not hard to add `--partitions` option and I'm not opposed to that if it is really critical for people. But the decision to omit it was intentional. We are moving towards as much configuration as possible being provided via the settings file, and we wanted to avoid having 2 ways of achieving the same thing and just supporting one.

Since settings is how nearly everything in Snuba is configured I would prefer for us to find a way to make it easy for self hosted users to configure their settings instead of adding back the CLI arg here, as it is likely to come up again for other settings that people might want to tweak.

**Comment by Jonas-Juvet** [comment]
@chadwhitacre How is this coming along? 

> I don't think we have a Snuba config file like we do for [Relay](https://github.com/getsentry/self-hosted/tree/2672ce545227f9a40b90178006c5ab25f7860a64/relay) and [Sentry](https://github.com/getsentry/self-hosted/tree/2672ce545227f9a40b90178006c5ab25f7860a64/sentry). Time to add one, it seems. :)

**Comment by chadwhitacre** [comment]
@ethanhs Did we ever end up with a self-hosted ticket for this?

**Comment by lynnagara** [comment]
@ethanhs Let's get a ticket for this in self-hosted (if there isn't one already)? Since settings is Snuba's canonical way for all configurations to be provided (not just this one) I think it should be a high priority to get this easily supported for users running Sentry self-hosted to provide overrides.

**Comment by Jonas-Juvet** [comment]
> @ethanhs Let's get a ticket for this in self-hosted (if there isn't one already)? Since settings is Snuba's canonical way for all configurations to be provided (not just this one) I think it should be a high priority to get this easily supported for users running Sentry self-hosted to provide overrides.

Did you guys create that ticket yet? 😅

**Comment by lynnagara** [comment]
Closing in favour of https://github.com/getsentry/self-hosted/issues/1836
