### ISSUE TITLE
Cannot Migrate when Clickhouse is hosted in a different Cluster and just exposed via one load balanced address.

### ISSUE THREAD

**Issue by LNCrafty** [getsentry/snuba#3235]
### Environment

What version are you running? Etc.
Latest. Every Version

### Steps to Reproduce

Just try to set the snuba config like this:

    CLUSTERS = [
      {
        "host": env("CLICKHOUSE_HOST", "external-load-balanced address"),
        "port": int(9000),
        "user":  env("CLICKHOUSE_USER", "default"),
        "password": env("CLICKHOUSE_PASSWORD", ""),
        "database": env("CLICKHOUSE_DATABASE", "default"),
        "http_port": 8123,
        "storage_sets": {
            "cdc",
            "discover",
            "events",
            "events_ro",
            "metrics",
            "migrations",
            "outcomes",
            "querylog",
            "sessions",
            "transactions",
            "transactions_ro",
            "transactions_v2",
            "errors_v2",
            "errors_v2_ro",
            "profiles",
            "replays",
            "generic_metrics_sets",
            "generic_metrics_distributions",
        },
        "single_node": False,
        "cluster_name": "replicated",
        "distributed_cluster_name": "replicated",
      },
    ]

### Expected Result

What you thought would happen.

suba migrates the stuff

### Actual Result
It tries to resolve all the cluster nodes that are not reachable and errors occur like this:
2022-10-11 14:48:09,602 Failed to connect to chi-x-frontend-analytic-replicated-0-0:9000
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 325, in connect
    return self._init_connection(host, port)
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 289, in _init_connection
    self.socket = self._create_socket(host, port)
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 241, in _create_socket
    for res in socket.getaddrinfo(host, port, 0, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
2022-10-11 14:48:09,705 Failed to connect to chi-analytic-replicated-0-0:9000
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 325, in connect
    return self._init_connection(host, port)
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 289, in _init_connection
    self.socket = self._create_socket(host, port)
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 241, in _create_socket
    for res in socket.getaddrinfo(host, port, 0, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
2022-10-11 14:48:09,808 Failed to connect to chi-analytic-replicated-0-0:9000

Another hint, why not use the "on cluster 'name of the cluster' method?
https://clickhouse.com/docs/en/sql-reference/distributed-ddl/

**Comment by volokluev** [comment]
What command are you running to get that error?

**Comment by volokluev** [comment]
Also, have you followed the steps here to enable distributed migrations?

https://getsentry.github.io/snuba/migrations/modes.html#enabling-distributed-mode

**Comment by lynnagara** [comment]
IIRC on cluster does not work with the current clickhouse versions we support

**Comment by LNCrafty** [comment]
so normally the snuba tries to access every instance of the cluster itself. So in my case I needed to create a extra pod where my clickhouse cluster was installed to run this migration. Because of the diffrent Kuberntes Clusters i have.
Personally I always migrate my stuff to clickhouse with the comamand ON CLUSTER. So is there maybe an option to use this command here too, insted of connecting to each node invidually?

Template for the migration. The config is above
          image: getsentry/snuba:22.10.0
          command:
            - snuba
            - migrations
            - migrate
            - '--force'

**Comment by dbanda** [comment]
That's a fair suggestion, but there are cases where cluster could be different from the host and you would have to encode the cluster name into the SQL of your migrations.

Generally, I'd say Snuba is meant to be run in a pod that has access to the nodes as its a core internal component. There isn't too much of a security difference doing otherwise, because, as you rightly pointed out, tables can still be written  using the `ON CLUSTER` cause.

If you must do it this way, you can create a cluster with only the host node, then add the `ON CLUSTER` clause to each of the SQL ddl queries in the migrations files.
