### ISSUE TITLE
consumers raise TimeoutError() exception 

### ISSUE THREAD

**Issue by bumarcell** [getsentry/snuba#3426]
### Environment

Self hosted sentry 22.10 in k8s

### Steps to Reproduce

1. Sessions or outcomes consumer consumes from kafka and tries to write to clickhouse
2. Clickhouse query takes more than 10sec
3. Consumer crashes with timeout exception

### Expected Result

Consumer should timeout without exception and/or have the option to set this timeout (here: https://github.com/getsentry/arroyo/pull/104)

### Actual Result

`2022-10-05 07:40:55,262 Completed processing <Batch: 5 messages, open for 3.33 seconds>.
2022-10-05 07:41:01,502 Caught TimeoutError(), shutting down...
2022-10-05 07:41:01,502 Terminating <snuba.consumers.consumer.ProcessedMessageBatchWriter object at 0x7f3f05c97f70>...
2022-10-05 07:41:01,503 Closing <arroyo.backends.kafka.consumer.KafkaConsumer object at 0x7f3f05d241c0>...
2022-10-05 07:41:01,503 Partitions revoked: [Partition(topic=Topic(name='ingest-sessions'), index=0)]
2022-10-05 07:41:01,504 Processor terminated
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/consumer.py", line 188, in consumer
    consumer.run()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 131, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 166, in _run_once
    self.__processing_strategy.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/streaming/transform.py", line 63, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/streaming/collect.py", line 135, in poll
    self.close_and_reset_batch()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/streaming/collect.py", line 199, in close_and_reset_batch
    self.future.result(timeout=5)
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 446, in result
    raise TimeoutError()
concurrent.futures._base.TimeoutError`

**Comment by masinette** [comment]
Hello @bumarcell,

Unfortunately, the Kubernetes platform is not currently supported. For more info on self-hosted Sentry, please see here: https://develop.sentry.dev/self-hosted/support/.

**Comment by randrusiak** [comment]
@masinette Why was this issue closed? The problem it's not strictly related to k8s but with a hardcoded timeout value.
