### ISSUE TITLE
Add possibility change timeout through env vars

### ISSUE THREAD

**Issue by artful88533** [getsentry/snuba#3749]
Hello!
I've got error in snuba-api:
```
2023-02-16 15:46:08,850 Error setting cache result!
Traceback (most recent call last):
  File "/usr/src/snuba/./snuba/state/cache/redis/backend.py", line 159, in get_readthrough
    value = self.__executor.submit(function).result(task_timeout)
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 446, in result
    raise TimeoutError()
concurrent.futures._base.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/snuba/./snuba/state/cache/redis/backend.py", line 164, in get_readthrough
    raise TimeoutError("timed out waiting for value") from error
TimeoutError: timed out waiting for value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/snuba/./snuba/state/cache/redis/backend.py", line 171, in get_readthrough
    self.__script_set(
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 2944, in __call__
    return client.evalsha(self.sha, len(keys), *args)
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 2079, in evalsha
    return self.execute_command('EVALSHA', sha, numkeys, *keys_and_args)
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/redis.py", line 101, in sentry_patched_execute_command
    return old_execute_command(self, name, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 668, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 680, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 629, in read_response
    raise response
redis.exceptions.ResponseError: invalid task id
2023-02-16 15:46:08,852 Error running query: SELECT (arrayElement(tags.value, indexOf(tags.key, 'ram_size_gb')) AS `_snuba_tags[ram_size_gb]`), (ifNull(uniq(`_snuba_tags[ram_size_gb]`), 0) AS _snuba_values_seen), (count() AS _snuba_count), (min((timestamp AS _snuba_timestamp)) AS _snuba_first_seen), (max(_snuba_timestamp) AS _snuba_last_seen) FROM errors_local PREWHERE in((project_id AS _snuba_project_id), tuple(42)) WHERE equals(deleted, 0) AND greaterOrEquals(_snuba_timestamp, toDateTime('2022-11-18T15:45:37', 'Universal')) AND less(_snuba_timestamp, toDateTime('2023-02-16T15:45:38', 'Universal')) AND notEquals(`_snuba_tags[ram_size_gb]`, '') AND 1 GROUP BY `_snuba_tags[ram_size_gb]` WITH TOTALS ORDER BY _snuba_count DESC LIMIT 3 OFFSET 0
timed out waiting for value
Traceback (most recent call last):
  File "/usr/src/snuba/./snuba/state/cache/redis/backend.py", line 159, in get_readthrough
    value = self.__executor.submit(function).result(task_timeout)
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 446, in result
    raise TimeoutError()
concurrent.futures._base.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/snuba/./snuba/web/db_query.py", line 432, in raw_query
    result = execute_query_strategy(
  File "/usr/src/snuba/./snuba/util.py", line 264, in wrapper
    return func(*args, **kwargs)
  File "/usr/src/snuba/./snuba/web/db_query.py", line 365, in execute_query_with_readthrough_caching
    return cache.get_readthrough(
  File "/usr/src/snuba/./snuba/state/cache/redis/backend.py", line 164, in get_readthrough
    raise TimeoutError("timed out waiting for value") from error
TimeoutError: timed out waiting for value
```

Do I understand correctly, that timeout is set here? 
https://github.com/getsentry/snuba/blob/master/snuba/web/db_query.py#L592

Could you add the possibility of customizing this parameter?

Many thanks for considering my request!

**Comment by volokluev** [comment]
This setting technically is configurable through the [runtime configuration](https://github.com/getsentry/snuba/blob/master/snuba/web/db_query.py#L603-L628), however even if you set it to a longer timeout it would not work as you expect.

The uwsgi server itself has a 30 second timeout, so even if you set that as longer, the server timeout would have to be changed as well.

Overall snuba is not meant to be serving queries longer than 30 seconds, it is meant to serve queries for the product UI. What are you trying to do with a query that long?

**Comment by artful88533** [comment]
> What are you trying to do with a query that long?

We have a project in sentry with a large number of events.
E.g. one issue contains 4,5M events. When I go to `Tags` and press the button `More Details` I get the error.

**Comment by artful88533** [comment]
@volokluev  Thanks for the answer!

Could you explain how to set runtime configuration and uwsgi timeout properly?
I'm running a sentry cluster in the docker

**Comment by volokluev** [comment]
I will prefix this by saying that this is undefined behavior and not supported. If you want to try and do this do the following:

1. Set the uwsgi `harakiri` option to the timeout you want
2. In the sentry redis, set the following value:

`HSET snuba_config max_execution_time <your timeout>`
