### ISSUE TITLE
Snuba migration error due to generic_metrics_counters

### ISSUE THREAD

**Issue by tosnoah** [getsentry/snuba#3798]
### Environment

Im trying to deploy sentry via the helm-chart on a kubernetes environment. Im using the latest Snuba (23.2.0)

### Steps to Reproduce

Some of the snuba migrations are failing and I can't see my snuba migrations list. 

### Expected Result

Trying to get the results of the migrations with the `snuba migrations list`

### Actual Result

`$ snuba migrations list
2023-02-28 09:06:26,312 Initializing Snuba...
2023-02-28 09:06:28,709 Snuba initialization took 2.3974769160849974s
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/migrations.py", line 30, in list
    for group, group_migrations in runner.show_all():
  File "/usr/src/snuba/snuba/migrations/runner.py", line 136, in show_all
    migration = group_loader.load_migration(migration_id)
  File "/usr/src/snuba/snuba/migrations/groups.py", line 75, in load_migration
    module = import_module(f"{self.__module}.{migration_id}")
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/src/snuba/snuba/snuba_migrations/generic_metrics/0010_counters_aggregate_table.py", line 23, in <module>
    class Migration(migration.ClickhouseNodeMigration):
  File "/usr/src/snuba/snuba/snuba_migrations/generic_metrics/0010_counters_aggregate_table.py", line 28, in Migration
    storage_set_key = StorageSetKey.GENERIC_METRICS_COUNTERS
  File "/usr/src/snuba/snuba/clusters/storage_sets.py", line 31, in __getattr__
    raise AttributeError(attr)
AttributeError: GENERIC_METRICS_COUNTERS`

Anyone any idea what might be causing this?

**Comment by creyD** [comment]
This appears to be an issue with the latest release, when downgrading to the previous version, this error disappears.

**Comment by cerealito** [comment]
I had the same issue. make sure you have "generic_metrics_counters" in your settings.py
```python
CLUSTERS = [
  {
    # ...
    "storage_sets": {
      # ...
      "generic_metrics_counters",
      # ...
    }
    # ...
  }
]
```
