### ISSUE TITLE
【subscriptions】Commit log cannot be partitioned

### ISSUE THREAD

**Issue by klboke** [getsentry/snuba#3799]
### Environment
snuba: 23.1.0

### Running services
```sh
snuba
subscriptions-scheduler
--entity=transactions
--auto-offset-reset=latest
--no-strict-offset-reset
--consumer-group=snuba-transactions-subscriptions-scheduler
--followed-consumer-group=transactions_group
--delay-seconds=1
--log-level=debug
--schedule-ttl=10
```
### Exception Stack
When running the subscriptions-scheduler service in our production environment, we encountered the following exception
```log
2023-02-28 17:16:57,519 Processor terminated
Traceback (most recent call last):
  File "/Users/kl/githubnamespace/snuba/.venv/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/kl/githubnamespace/snuba/.venv/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/kl/githubnamespace/snuba/.venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/kl/githubnamespace/snuba/.venv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/kl/githubnamespace/snuba/snuba/cli/subscriptions_scheduler.py", line 178, in subscriptions_scheduler
    processor.run()
  File "/Users/kl/githubnamespace/snuba/.venv/lib/python3.8/site-packages/arroyo/processing/processor.py", line 175, in run
    self._run_once()
  File "/Users/kl/githubnamespace/snuba/.venv/lib/python3.8/site-packages/arroyo/processing/processor.py", line 225, in _run_once
    self.__processing_strategy.submit(message)
  File "/Users/kl/githubnamespace/snuba/snuba/subscriptions/scheduler_processing_strategy.py", line 283, in submit
    self.__next_step.submit(self.__buffers[partition_index].popleft())
  File "/Users/kl/githubnamespace/snuba/snuba/subscriptions/scheduler_processing_strategy.py", line 90, in submit
    self.__update_offset_high_watermark(message.value)
  File "/Users/kl/githubnamespace/snuba/snuba/subscriptions/scheduler_processing_strategy.py", line 111, in __update_offset_high_watermark
    assert value.partition.index == 0, "Commit log cannot be partitioned"
AssertionError: Commit log cannot be partitioned
```
### Questions
The exception message obviously disables commit log partitioning, but this contradicts the following message

```python
class CombinedSchedulerExecutorFactory(ProcessingStrategyFactory[Tick]):
    """
    An alternative to the separate scheduler and executor which can be used to schedule
    and execute subscriptions for multiple entities in a dataset all at once. This is designed
    to be easier to run (less containers) but does not scale with subscription volume like
    the separate scheduler and executor.

    It should only be used in environments where:
    - there are relatively few subscriptions
    - the main topic only has a single partition (since offsets on the commit log
    are committed once a subscription has finished running - regardless of the
    original partition they came from)
    """
```
It is recommended that we use 'subscriptions-scheduler' rather than 'subscriptions-scheduler-executor' because separating 'scheduler' and 'executor' gives better scalability, but scaling the 'scheduler' service becomes pointless when the commit log has no partitioning support, right?
- @lynnagara request help , I would like to know if this is expected? Or any information to answer any doubts, thank you very much

### Additional
 Also, I found that the 'test_scheduler_consumer' test case doesn't work either, same problem as this one
https://github.com/getsentry/snuba/blob/25bac6b503356b2efbeca6f83ebea539fa561e15/tests/subscriptions/test_scheduler_consumer.py#L39

```python
Launching pytest with arguments test_scheduler_consumer.py::test_scheduler_consumer --no-header --no-summary -q in /Users/kl/githubnamespace/kl/snuba/tests/subscriptions

============================= test session starts ==============================
collecting ... collected 1 item

test_scheduler_consumer.py::test_scheduler_consumer FAILED               [100%]
tests/subscriptions/test_scheduler_consumer.py:38 (test_scheduler_consumer)
Traceback (most recent call last):
  File "/Users/kl/githubnamespace/kl/snuba/tests/subscriptions/test_scheduler_consumer.py", line 130, in test_scheduler_consumer
    scheduler._run_once()
  File "/Users/kl/githubnamespace/kl/snuba/.venv/lib/python3.8/site-packages/arroyo/processing/processor.py", line 225, in _run_once
    self.__processing_strategy.submit(message)
  File "/Users/kl/githubnamespace/kl/snuba/snuba/subscriptions/scheduler_processing_strategy.py", line 240, in submit
    self.__next_step.submit(message)
  File "/Users/kl/githubnamespace/kl/snuba/snuba/subscriptions/scheduler_processing_strategy.py", line 90, in submit
    self.__update_offset_high_watermark(message.value)
  File "/Users/kl/githubnamespace/kl/snuba/snuba/subscriptions/scheduler_processing_strategy.py", line 111, in __update_offset_high_watermark
    assert value.partition.index == 0, "Commit log cannot be partitioned"
AssertionError: Commit log cannot be partitioned
```

**Comment by lynnagara** [comment]
Hi @klboke, the commit log will have very few messages even in high throughput scenarios, and it's only job is to periodically track progress on a main topic, e.g. `snuba-commit-log` follows the `events` topic. So: `events` can have multiple partitions but `snuba-commit-log` must only ever have only one.

The combined scheduler/executor is supposed to provide a more convenient alternative to the separate subscriptions-scheduler and subscriptions-executor processors for self hosted users. In environments with large numbers of subscriptions, they are separate because there is only one scheduler, but there can be as multiple executor processes as needed. The combined scheduler and executor does assume that both `events` AND `snuba-commit-log` only have one partition. (If that's not true and there are actually multiple partitions in `events`, it does still work but note that we lose the at-least-once guarantees and it is possible that subscriptions/alerts occasionally do not fire.)

**Comment by klboke** [comment]
I think I understand why it was designed that way. And I also noticed why my local 'test_scheduler_consumer' test case didn't work because I already had a local kafka instance, which caused the kafka simulation to fail when running the test case, so.  thanks again for the detailed explanation
