### ISSUE TITLE
kafka retentions_days value is null and cause snuba cosumers restarting

### ISSUE THREAD

**Issue by Seanotyet** [getsentry/snuba#3853]
### Environment

What version are you running? Etc.
23.1.1 in Self-hosted sentry

### Steps to Reproduce

When post data to self-hosted sentry saw the following errors.
```2023-03-13 06:06:03,977 Closing <arroyo.backends.kafka.consumer.KafkaConsumer object at 0x7f017fba9bb0>...
2023-03-13 06:06:03,977 Partitions revoked: [Partition(topic=Topic(name='events'), index=0)]
2023-03-13 06:06:03,979 Processor terminated
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 564, in process_message
    result = processor.process_message(
  File "/usr/src/snuba/snuba/datasets/processors/errors_processor.py", line 61, in process_message
    row = self.process_insert(event, metadata)
  File "/usr/src/snuba/snuba/datasets/processors/errors_processor.py", line 84, in process_insert
    processed["retention_days"] = enforce_retention(
  File "/usr/src/snuba/snuba/datasets/events_format.py", line 125, in enforce_retention
    datetime.utcnow() - timedelta(days=retention_days)
TypeError: unsupported type for timedelta days component: str

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/consumer.py", line 189, in consumer
    consumer.run()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 181, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 231, in _run_once
    self.__processing_strategy.submit(message)
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/run_task.py", line 66, in submit
    result = self.__function(cast(Message[TStrategyPayload], message))
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 576, in process_message
    raise InvalidMessages(
arroyo.processing.strategies.dead_letter_queue.invalid_messages.InvalidMessages: [InvalidKafkaMessage(payload=b'[2,"insert",{"group_id":70,"group_ids":[70],"event_id":"6cb8e5c00196444e998bcfba7ac30a8c","organization_id":1,"project_id":9,"message":"a False","platform":"javascript","datetime":"2023-03-13T06:06:01.542000Z","data":{"event_id":"6cb8e5c00196444e998bcfba7ac30a8c","level":"error","version":"7","type":"error","logentry":{"formatted":"a","message":null,"params":null},"logger":"","platform":"javascript","timestamp":1678687561.542,"received":1678687562.763267,"environment":"production","user":{"ip_address":"10.32.49.176"},"request":{"url":"http://localhost:3001/","fragment":"/","headers":[["Referer","http://localhost:3001/"],["User-Agent","Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36"]],"query_string":[],"method":null,"cookies":null,"data":null,"env":null,"inferred_content_type":null},"contexts":{"browser":{"name":"Chrome","version":"110.0.0","type":"browser"},"device":{"family":"Mac","model":"Mac","brand":"Apple","type":"device"},"os":{"name":"Mac OS X","version":"10.15.7","type":"os"}},"exception":{"values":[{"type":"Error","value":"a","mechanism":{"type":"generic","synthetic":true,"handled":true,"description":null,"help_link":null,"data":null,"meta":null}}]},"sdk":{"name":"sentry.javascript.browser","version":"7.42.0","integrations":["InboundFilters","FunctionToString","TryCatch","Breadcrumbs","GlobalHandlers","LinkedErrors","Dedupe","HttpContext"],"packages":[{"name":"npm:@sentry/browser","version":"7.42.0"}]},"key_id":"9","project":9,"grouping_config":{"enhancements":"eJybzDRxY3J-bm5-npWRgaGlroGxrpHxBABcYgcZ","id":"newstyle:2019-10-29"},"_metrics":{"bytes.ingested.event":755,"bytes.stored.event":1985},"tags":[["level","error"],["environment","production"],["sentry:user","ip:10.32.49.176"],["url","http://localhost:3001/"],["mechanism","generic"],["handled","yes"],["browser","Chrome 110.0.0"],["browser.name","Chrome"],["device","Mac"],["device.family","Mac"],["os","Mac OS X 10.15.7"],["os.name","Mac OS X"]],"fingerprint":["{{ default }}"],"hashes":["0cc175b9c0f1b6a831c399e269772661"],"culprit":"","metadata":{"value":"a","display_title_with_tree_label":false},"title":"<unknown>","location":null,"_ref":9,"_ref_version":2,"nodestore_insert":1678687563.839689},"primary_hash":"0cc175b9c0f1b6a831c399e269772661","retention_days":null,"occurrence_id":null,"occurrence_data":{}},{"is_new":false,"is_regression":false,"is_new_group_environment":false,"queue":"post_process_errors","skip_consume":false,"group_states":[{"id":70,"is_new":false,"is_regression":false,"is_new_group_environment":false}]}]', timestamp=datetime.datetime(2023, 3, 13, 6, 6, 3, 845000), topic='events', consumer_group='snuba-consumers', partition=0, offset=88, headers=[('Received-Timestamp', b'1678687562.763267'), ('event_id', b'6cb8e5c00196444e998bcfba7ac30a8c'), ('project_id', b'9'), ('group_id', b'70'), ('primary_hash', b'0cc175b9c0f1b6a831c399e269772661'), ('is_new', b'0'), ('is_new_group_environment', b'0'), ('is_regression', b'0'), ('skip_consume', b'0'), ('group_states', b'[{"id":70,"is_new":false,"is_regression":false,"is_new_group_environment":false}]'), ('queue', b'post_process_errors'), ('operation', b'insert'), ('version', b'2')], key=b'9', reason='TypeError: unsupported type for timedelta days component: str')]
2023-03-13 06:06:05,509 Initializing Snuba...
2023-03-13 06:06:07,563 Snuba initialization took 2.0548839829862118s```



### Expected Result

What you thought would happen.
Hi Sentry teams, Could you help with the issue?
It may relate to ""retention_days":null" in kafka eventstopic, how to set the default for retention_days?

**Comment by Seanotyet** [comment]
Caused by lost the https://github.com/getsentry/self-hosted/blob/master/sentry/sentry.conf.example.py#L62 in sentry.conf.py, the error gone after added.
