### ISSUE TITLE
can't migrate from 22.4.0 to 23.4.0 because of missing replays attribute

### ISSUE THREAD

**Issue by gromnsk** [getsentry/snuba#4090]
### Environment

I'm trying to update from 22.4.0 to 23.4.0

### Steps to Reproduce

when I'm trying to update sentry 22.4.0 to 23.4.0 I've got an error that `Replays` is not found, as I can see in code here https://github.com/getsentry/snuba/blob/23.4.0/snuba/snuba_migrations/replays/0001_replays.py#L97 it's using replays storageSetKey, but https://github.com/getsentry/snuba/blob/23.4.0/snuba/clusters/storage_sets.py#L5 here `replays` key was removed, is it okay and I'm doing something wrong or is that a bug? 

### Expected Result

migration passed successfully

### Actual Result

in `snuba migrations migrate --force` I've got next error:

> 2023-04-26 10:59:11,469 Block "" send time: 0.000026
> Traceback (most recent call last):
>   File "/usr/local/bin/snuba", line 33, in <module>
>     sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
>   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
>     rv = self.invoke(ctx)
>   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
>     return __callback(*args, **kwargs)
>   File "/usr/src/snuba/snuba/cli/migrations.py", line 96, in migrate
>     runner.run_all(
>   File "/usr/src/snuba/snuba/migrations/runner.py", line 216, in run_all
>     self._run_migration_impl(migration_key, force=force)
>   File "/usr/src/snuba/snuba/migrations/runner.py", line 280, in _run_migration_impl
>     migration.forwards(context, dry_run)
>   File "/usr/src/snuba/snuba/migrations/migration.py", line 126, in forwards
>     ops = self.forwards_ops()
>   File "/usr/src/snuba/snuba/migrations/migration.py", line 236, in forwards_ops
>     local_ops, dist_ops = self.forwards_local(), self.forwards_dist()
>   File "/usr/src/snuba/snuba/snuba_migrations/replays/0001_replays.py", line 65, in forwards_local
>     storage_set=StorageSetKey.REPLAYS,
>   File "/usr/src/snuba/snuba/clusters/storage_sets.py", line 31, in __getattr__
>     raise AttributeError(attr)
> AttributeError: REPLAYS

**Comment by volokluev** [comment]
@gromnsk apologies for the issues. When you run 

`snuba migrations migrate --force`

Do you have the following loglines in your terminal?

```
2023-05-02 15:02:28,809 Initializing Snuba...
2023-05-02 15:02:31,520 Snuba initialization took 2.712432358s
```

**Comment by gromnsk** [comment]
@volokluev sorry for delay, I've returned back to this task and trying to upgrade again. Now I'm trying to upgrade step by step from 22.4.0 to the latest version and stuck on 22.6.0 version. When I'm trying to apply migrations I've got this:
`snuba migrations migrate --force
2023-06-15 09:18:54,922 Attempting to connect to Clickhouse cluster localhost:9000 (attempt 0)
2023-06-15 09:18:54,926 Connecting. Database: default. User: default
2023-06-15 09:18:54,926 Connecting to localhost:9000
2023-06-15 09:18:54,930 Connected to ClickHouse server version 20.8.19, revision: 54438
2023-06-15 09:18:54,931 Query: SELECT version()
2023-06-15 09:18:54,931 Block "" send time: 0.000291
2023-06-15 09:18:54,935 Query: SELECT group, migration_id, status FROM migrations_dist FINAL WHERE group IN ('system', 'events', 'transactions', 'discover', 'outcomes', 'metrics', 'sessions', 'generic_metrics')
2023-06-15 09:18:54,935 Block "" send time: 0.000196
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/migrations.py", line 64, in migrate
    runner.run_all(force=force)
  File "/usr/src/snuba/snuba/migrations/runner.py", line 145, in run_all
    pending_migrations = self._get_pending_migrations()
  File "/usr/src/snuba/snuba/migrations/runner.py", line 297, in _get_pending_migrations
    raise MigrationInProgress(str(migration_key))
snuba.migrations.errors.MigrationInProgress: generic_metrics: 0001_sets_aggregate_table`

I'm trying to revert this migration, but unfortunately it's not working too
`snuba migrations reverse --group generic_metrics --migration-id 0001_sets_aggregate_table
2023-06-15 09:19:57,223 Attempting to connect to Clickhouse cluster localhost:9000 (attempt 0)
2023-06-15 09:19:57,227 Connecting. Database: default. User: default
2023-06-15 09:19:57,228 Connecting to localhost:9000
2023-06-15 09:19:57,231 Connected to ClickHouse server version 20.8.19, revision: 54438
2023-06-15 09:19:57,232 Query: SELECT version()
2023-06-15 09:19:57,232 Block "" send time: 0.000068
2023-06-15 09:19:57,236 Query: SELECT group, migration_id, status FROM migrations_dist FINAL WHERE group IN ('system', 'events', 'transactions', 'discover', 'outcomes', 'metrics', 'sessions', 'generic_metrics')
2023-06-15 09:19:57,236 Block "" send time: 0.000043
2023-06-15 09:19:57,246 Reversing migration: 0001_sets_aggregate_table
2023-06-15 09:19:57,247 Query: SELECT version FROM migrations_dist FINAL WHERE group = 'generic_metrics' AND migration_id = '0001_sets_aggregate_table';
2023-06-15 09:19:57,247 Block "" send time: 0.000056
2023-06-15 09:19:57,259 Query: INSERT INTO migrations_dist FORMAT JSONEachRow
2023-06-15 09:19:57,259 Block "" send time: 0.000036
2023-06-15 09:19:57,263 Block "" send time: 0.002586
2023-06-15 09:19:57,263 Block "" send time: 0.000044
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/migrations.py", line 160, in reverse
    runner.reverse_migration(migration_key, force=force, fake=fake)
  File "/usr/src/snuba/snuba/migrations/runner.py", line 262, in reverse_migration
    self._reverse_migration_impl(migration_key)
  File "/usr/src/snuba/snuba/migrations/runner.py", line 276, in _reverse_migration_impl
    migration.backwards(context, dry_run)
  File "/usr/src/snuba/snuba/migrations/migration.py", line 160, in backwards
    op.execute(local=False)
  File "/usr/src/snuba/snuba/migrations/operations.py", line 21, in execute
    cluster = get_cluster(self._storage_set)
  File "/usr/src/snuba/snuba/clusters/cluster.py", line 405, in get_cluster
    raise UndefinedClickhouseCluster(
snuba.clusters.cluster.UndefinedClickhouseCluster: StorageSetKey.GENERIC_METRICS_SETS is not a defined in the CLUSTERS setting for this environment`

in clickhouse I have 2 versions of this migration in status `in_progress`, have no idea why there is 2 rows
`┌─group───────────┬─migration_id──────────────┬───────────timestamp─┬─status──────┬─version─┐
│ generic_metrics │ 0001_sets_aggregate_table │ 2023-06-15 08:24:12 │ in_progress │       1 │
└─────────────────┴───────────────────────────┴─────────────────────┴─────────────┴─────────┘
┌─group───────────┬─migration_id──────────────┬───────────timestamp─┬─status──────┬─version─┐
│ generic_metrics │ 0001_sets_aggregate_table │ 2023-06-15 08:44:58 │ in_progress │       2 │
└─────────────────┴───────────────────────────┴─────────────────────┴─────────────┴─────────┘`

any idea what's wrong and how can I fix it?

**Comment by gromnsk** [comment]
I found a problem, the issue was that I forgot to update my custom settings.py
