### ISSUE TITLE
Migration - main thread column

### ISSUE THREAD

**Issue by strnky** [getsentry/snuba#4133]
### Environment

Sentry on-premise 23.2.0 running in k8s.

### Steps to Reproduce

image: snuba: 23.4.0

same with snuba: 23.3.1

```bash
snuba migrations migrate --force
```

### Actual Result
```
2023-05-04 06:59:24,412 Initializing Snuba...
2023-05-04 06:59:26,963 Snuba initialization took 2.5515421256422997s
2023-05-04 06:59:26,965 Attempting to connect to Clickhouse cluster hpo-clickhouse:9000 (attempt 0)
2023-05-04 06:59:26,969 Connecting. Database: default. User: default
2023-05-04 06:59:26,969 Connecting to hpo-clickhouse:9000
2023-05-04 06:59:26,972 Connected to ClickHouse server version 22.7.3, revision: 54457
2023-05-04 06:59:26,973 Query: SELECT version()
2023-05-04 06:59:26,973 Block "" send time: 0.000107
2023-05-04 06:59:26,983 Query: SELECT group, migration_id, status FROM migrations_dist FINAL WHERE group IN ('system', 'events', 'transactions', 'discover', 'outcomes', 'metrics', 'sessions', 'replays', 'generic_metrics')
2023-05-04 06:59:26,983 Block "" send time: 0.000094
2023-05-04 06:59:26,998 Query: SELECT group, migration_id, status FROM migrations_dist FINAL WHERE group IN ('system', 'events', 'transactions', 'discover', 'outcomes', 'metrics', 'sessions', 'replays', 'generic_metrics')
2023-05-04 06:59:26,998 Block "" send time: 0.000109
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/migrations.py", line 74, in migrate
    runner.run_all(force=force, group=migration_group)
  File "/usr/src/snuba/snuba/migrations/runner.py", line 163, in run_all
    pending_migrations = self._get_pending_migrations()
  File "/usr/src/snuba/snuba/migrations/runner.py", line 350, in _get_pending_migrations
    group_migrations = self._get_pending_migrations_for_group(group)
  File "/usr/src/snuba/snuba/migrations/runner.py", line 373, in _get_pending_migrations_for_group
    raise MigrationInProgress(str(migration_key))
snuba.migrations.errors.MigrationInProgress: events: 0020_add_main_thread_column
```

**Comment by enochtangg** [comment]
Hi @strnky, the error you are experiencing occurs when trying to execute a migration that is currently set to `STATUS=IN_PROGRESS`. One possibility is that snuba might have crashed during the first migration execution, causing the status to be stuck "in progress". One solution is reverting the migration (via https://github.com/getsentry/snuba/blob/master/MIGRATIONS.md#reverse-a-single-migration) and re-running it. Could you give that a try, and let me know if it fixes things?

**Comment by strnky** [comment]
Hi @enochtangg,
yes, this is it, thank You for your advice.
