### ISSUE TITLE
Sentry Update from 22.3 to 23.4 Results in Snuba Service Error

### ISSUE THREAD

**Issue by 3JIou-home** [getsentry/snuba#4237]
### Environment

- Kubernetes
- Sentry version 23.4.0 (Updated from 22.3)
- Snuba version (part of Sentry 23.4.0)
- Timezone: Asia/Almaty

### Description:
After updating Sentry from version 22.3 to 23.4, we encountered an error in the snuba-messaging-subscriptions-events-job service. This error causes the service to shut down.

### Steps to Reproduce

1. Update Sentry from version 22.3 to 23.4.
2. Observe the error in the snuba-messaging-subscriptions-events-job service logs.

### Expected Result

The service should run without any errors.

### Actual Result

An error occurs during the execution of the service, which results in a shutdown. 

```
2023-05-19 14:52:12,803 New partitions assigned: {Partition(topic=Topic(name='snuba-commit-log'), index=0): 82704} 
2023-05-19 14:52:12,804 Initialized processing strategy: <snuba.subscriptions.scheduler_processing_strategy.TickBuffer object at 0x7fc466612520>
2023-05-19 14:52:12,810 Caught exception, shutting down... 
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 200, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 287, in _run_once
    self.__processing_strategy.submit(message)
  File "/usr/src/snuba/snuba/subscriptions/scheduler_processing_strategy.py", line 240, in submit
    self.__next_step.submit(message)
  File "/usr/src/snuba/snuba/subscriptions/combined_scheduler_executor.py", line 246, in submit
    tasks.extend([task for task in entity_scheduler[tick.partition].find(tick)])
KeyError: 1
2023-05-19 14:52:12,812 Terminating <snuba.subscriptions.scheduler_processing_strategy.TickBuffer object at 0x7fc466612520>...
2023-05-19 14:52:12,812 Closing <snuba.subscriptions.scheduler_consumer.CommitLogTickConsumer object at 0x7fc464e55310>...
2023-05-19 14:52:12,813 Partitions revoked: [Partition(topic=Topic(name='snuba-commit-log'), index=0)] 
2023-05-19 14:52:12,814 Processor terminated
```    

#### Service run configuration:

```
image: docker-hub-cache.foo.bar:5000/getsentry/snuba:23.4.0
imagePullPolicy: Always
resources:
  requests:
    cpu: "3000m"
    memory: "384Mi"
  limits:
    cpu: "5000m"
    memory: "512Mi"
envFrom:
  - configMapRef:
      name: sentry21-snuba

env:
  - name: TZ
    value: "Asia/Almaty"

command: ["snuba", "subscriptions-scheduler-executor",
    "--dataset", "events",
    "--entity", "events",
    "--auto-offset-reset=latest",
    "--no-strict-offset-reset",
    "--consumer-group=snuba-events-subscriptions-consumers",
    "--followed-consumer-group=snuba-consumers",
    "--delay-seconds=60",
    "--schedule-ttl=60",
    "--total-concurrent-queries", "5",
    "--log-level", "DEBUG",
    "--stale-threshold-seconds=900"]
```   

#### Snuba settings:

```
SNUBA_SETTINGS: "distributed"
UWSGI_MAX_REQUESTS: "20000"
UWSGI_DISABLE_LOGGING: "true"
CLICKHOUSE_HOST: "sentry-clickhouse.foo.bar"
CLICKHOUSE_PORT: "9000"
CLICKHOUSE_SINGLE_NODE: "true"
REDIS_HOST: "sentry-redis1.foo.bar"
REDIS_PORT: "6379"
TOPIC_PARTITION_COUNTS: |
  {
    "events": 6,
    "outcomes": 3,
    "ingest-events": 3,
    "ingest-sessions": 3,
    "ingest-transactions": 3
  }
DEFAULT_BROKERS: "sentry-redpanda1.foo.bar:9092,sentry-redpanda2.foo.bar:9092,sentry-redpanda3.foo.bar:9092"
```

### Additional Information:

We use Redpanda instead of Kafka. The configurations for the 'snuba-commit-log' queue are as follows:

```
SUMMARY
=======
NAME        snuba-commit-log
PARTITIONS  1
REPLICAS    1

CONFIGS
=======
KEY                           VALUE       SOURCE
cleanup.policy                delete      DEFAULT_CONFIG
compression.type              producer    DEFAULT_CONFIG
max.message.bytes             1048576     DEFAULT_CONFIG
message.timestamp.type        CreateTime  DYNAMIC_TOPIC_CONFIG
redpanda.remote.delete        true        DEFAULT_CONFIG
redpanda.remote.read          false       DEFAULT_CONFIG
redpanda.remote.write         false       DEFAULT_CONFIG
retention.bytes               -1          DEFAULT_CONFIG
retention.local.target.bytes  -1          DEFAULT_CONFIG
retention.local.target.ms     86400000    DEFAULT_CONFIG
retention.ms                  3600000     DYNAMIC_TOPIC_CONFIG
segment.bytes                 536870912   DEFAULT_CONFIG
segment.ms                    1209600000  DEFAULT_CONFIG
```

When the process starts, it puts the group into rebalance and then crashes:

```
GROUP        snuba-events-subscriptions-consumers
COORDINATOR  3
BALANCER     PreparingRebalance
MEMBERS      0
``` 

The same result is observed when launching the service with the 'subscriptions-scheduler' command:

```
snuba subscriptions-scheduler --entity events --consumer-group snuba-events-subscriptions-consumers --auto-offset-reset latest --no-strict-offset-reset  --followed-consumer-group snuba-consumers
```

I suspect that the problem may be related to time, but I can't confirm this. I also noticed that when changing the offset, the process processes a few messages and then crashes:

```
TOPIC             PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG    MEMBER-ID  CLIENT-ID  HOST
snuba-commit-log  0          738             64038           63300
```

**Comment by lynnagara** [comment]
We're working to get rid of this but for now you need to update Snuba's topic partition count settings with the number of partitions you have on events topics in your settings file.

https://github.com/getsentry/snuba/blob/c23cc180cecfeac838bbd9a42928e5b59aa159cd/snuba/settings/__init__.py#L255

in your case:
```
TOPIC_PARTITION_COUNTS = {
  "events": 6,
}
```
