### ISSUE TITLE
Subscribed topic not available: outcomes: Broker: Unknown topic or partition

### ISSUE THREAD

**Issue by herolyle** [getsentry/snuba#4283]
[root@docker-desktop click]# DEBUG=1 SNUBA_SETTINGS=self_hosted REDIS_HOST=127.0.0.1 DEFAULT_BROKERS="10.6.3.228:9092"  snuba consumer --storage outcomes_raw --auto-offset-reset=earliest --max-batch-time-ms 750 --no-strict-offset-reset
2023-06-03 14:17:14,695 Initializing Snuba...
2023-06-03 14:17:17,385 Snuba initialization took 2.6905336300260387s
2023-06-03 14:17:17,409 Consumer Starting
2023-06-03 14:17:17,410 librdkafka log level: 6
2023-06-03 14:17:17,822 Caught exception, shutting down...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 290, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 357, in _run_once
    self.__message = self.__consumer.poll(timeout=1.0)
  File "/usr/local/lib/python3.8/site-packages/arroyo/backends/kafka/consumer.py", line 409, in poll
    raise ConsumerError(str(error))
arroyo.errors.ConsumerError: KafkaError{code=UNKNOWN_TOPIC_OR_PART,val=3,str="Subscribed topic not available: outcomes: Broker: Unknown topic or partition"}
2023-06-03 14:17:17,823 Closing <arroyo.backends.kafka.consumer.KafkaConsumer object at 0x7f8a83d0e100>...
2023-06-03 14:17:17,825 Processor terminated
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/app/snuba/snuba/cli/consumer.py", line 221, in consumer
    consumer.run()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 290, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 357, in _run_once
    self.__message = self.__consumer.poll(timeout=1.0)
  File "/usr/local/lib/python3.8/site-packages/arroyo/backends/kafka/consumer.py", line 409, in poll
    raise ConsumerError(str(error))
arroyo.errors.ConsumerError: KafkaError{code=UNKNOWN_TOPIC_OR_PART,val=3,str="Subscribed topic not available: outcomes: Broker: Unknown topic or partition"}

**Comment by klboke** [comment]
Creating the topic 'outcomes' manually can solve this problem." This means that you need to manually create a topic named "outcomes" in the system to resolve the issue. A topic is a named entity used for messaging in a messaging system. In this problem, there may be a program or system that is attempting to send a message to a topic named "outcomes," but the topic has not yet been created in the system. Therefore, you need to manually create the topic so that the program or system can send and receive messages correctly

**Comment by lynnagara** [comment]
fyi @hubertdeng123

**Comment by lynnagara** [comment]
Running `snuba bootstrap` should create this (along with the other topics). Afaik this command is run on any self hosted install/upgrade.

**Comment by hubertdeng123** [comment]
Are you using the [docker compose version of self-hosted](https://github.com/getsentry/self-hosted)? Echoing what was mentioned above, bootstrapping snuba is done on every install/upgade [here](https://github.com/getsentry/self-hosted/blob/e07be386ee5fcbcbb271d17c7bd5a94c28e8caac/install/bootstrap-snuba.sh).
