### ISSUE TITLE
sentry-snuba-subscription-consumer-sessions restart in self hosted sentry

### ISSUE THREAD

**Issue by lcc3108** [getsentry/snuba#4440]
### Environment
eks self host sentry

### Steps to Reproduce

The current snuba-sessions-commit-log partition is 1.

I tried adding the values below because they didn't work with the default settings, but they didn't work.

```
snubaSettingsPy: |
# # No Python Extension Config Given
TOPIC_PARTITION_COUNTS = {"snuba-sessions-commit-log": 1}
```
### Expected Result

normaly running
### Actual Result

```
2023-06-29 05:55:30,316 Initializing Snuba...
2023-06-29 05:55:34,889 Snuba initialization took 4.5744772949256s
2023-06-29 05:55:38,142 New partitions assigned: {Partition(topic=Topic(name='snuba-sessions-commit-log'), index=0): 44445}
2023-06-29 05:55:38,169 Caught exception, shutting down...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 282, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 376, in _run_once
    self.__processing_strategy.submit(message)
  File "/usr/src/snuba/snuba/subscriptions/scheduler_processing_strategy.py", line 240, in submit
    self.__next_step.submit(message)
  File "/usr/src/snuba/snuba/subscriptions/combined_scheduler_executor.py", line 246, in submit
    tasks.extend([task for task in entity_scheduler[tick.partition].find(tick)])
KeyError: 1
2023-06-29 05:55:38,171 Closing <snuba.subscriptions.scheduler_consumer.CommitLogTickConsumer object at 0x7f439842fe80>...
2023-06-29 05:55:38,173 Partitions to revoke: [Partition(topic=Topic(name='snuba-sessions-commit-log'), index=0)]
2023-06-29 05:55:38,173 on_partitions_revoked crashed
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 282, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 376, in _run_once
    self.__processing_strategy.submit(message)
  File "/usr/src/snuba/snuba/subscriptions/scheduler_processing_strategy.py", line 240, in submit
    self.__next_step.submit(message)
  File "/usr/src/snuba/snuba/subscriptions/combined_scheduler_executor.py", line 246, in submit
    tasks.extend([task for task in entity_scheduler[tick.partition].find(tick)])
KeyError: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 46, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 223, in on_partitions_revoked
    _close_strategy()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 161, in _close_strategy
    raise InvalidStateError(
arroyo.processing.processor.InvalidStateError: received unexpected revocation without active processing strategy
2023-06-29 05:55:38,178 Processor terminated
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/subscriptions_scheduler_executor.py", line 141, in subscriptions_scheduler_executor
    processor.run()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 282, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 376, in _run_once
    self.__processing_strategy.submit(message)
  File "/usr/src/snuba/snuba/subscriptions/scheduler_processing_strategy.py", line 240, in submit
    self.__next_step.submit(message)
  File "/usr/src/snuba/snuba/subscriptions/combined_scheduler_executor.py", line 246, in submit
    tasks.extend([task for task in entity_scheduler[tick.partition].find(tick)])
KeyError: 1
```

**Comment by lynnagara** [comment]
The commit log tracks progress on the main "ingest-sessions" topic. How many partitions do you have there?
For example if you have 2, your config should look like:
```
TOPIC_PARTITION_COUNTS = {"ingest-sessions": 2}
```

**Comment by chadwhitacre** [comment]
@lynnagara I updated the labels based on your comment, in future please apply "Waiting for: Community" after posing a question, it helps us keep track of how well we're on top of conversations and will also kick in stalebot when users ghost us. 👻 😌

**Comment by chadwhitacre** [comment]
(And if you're just acknowledging an issue without needing more info then remove `Waiting for: Product Owner`. 🙏)

**Comment by luugh** [comment]
> 提交日志跟踪主要“摄取会话”主题的进度。你那里有多少个分区？ 例如，如果您有 2 个，您的配置应如下所示：
> 
> ```
> TOPIC_PARTITION_COUNTS = {"ingest-sessions": 2}
> ```
我遇到了相同的问题，我按照实际的分区配置了TOPIC_PARTITION_COUNTS = {"ingest-sessions": 6}后，仍旧报一样的错

**Comment by luugh** [comment]
> The commit log tracks progress on the main "ingest-sessions" topic. How many partitions do you have there? For example if you have 2, your config should look like:
> 
> ```
> TOPIC_PARTITION_COUNTS = {"ingest-sessions": 2}
> ```

I'm having the same problem, I configure TOPIC_PARTITION_COUNTS = {"ingest-sessions": 6} according to the actual partition, the error still occurs.

**Comment by lynnagara** [comment]
@luugh Not sure what your exact stack trace is but you'll need the same for the other topics as well where you've increased partitions, not just `ingest-sessions`.

**Comment by luugh** [comment]
> @luugh Not sure what your exact stack trace is but you'll need the same for the other topics as well where you've increased partitions, not just `ingest-sessions`. (the one posted originally was about sessions)

Yes, I changed the code to output the topic to the log and found that the topic that reported the error was: transactions
