### ISSUE TITLE
Snuba migrations do not complete successfully

### ISSUE THREAD

**Issue by ggolin** [getsentry/snuba#4538]
### Environment

Snuba 23.7.0 in a Sentry k8s deployment, latest chart
ClickHouse server version 23.4.6.25 (official build).

### Steps to Reproduce

1. Run `snuba bootstrap --force --no-migrate` 
2. Run `snuba migrations migrate --force`

### Expected Result

Migrations complete successfuly.

### Actual Result

A trace is generated:
```
snuba@sentry-snuba-api-69879458bb-85cfh:/usr/src/snuba$ snuba migrations migrate --force
2023-07-19 03:31:24,124 Initializing Snuba...
2023-07-19 03:31:26,155 Snuba initialization took 2.032084882259369s
2023-07-19 03:31:26,205 Running migration: 0001_migrations
2023-07-19 03:31:26,222 Finished: 0001_migrations
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/clickhouse/native.py", line 192, in execute
    result_data = query_execute()
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 304, in execute
    rv = self.process_ordinary_query(
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 491, in process_ordinary_query
    return self.receive_result(with_column_types=with_column_types,
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 151, in receive_result
    return result.get_result()
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/result.py", line 50, in get_result
    for packet in self.packet_generator:
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 167, in packet_generator
    packet = self.receive_packet()
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 184, in receive_packet
    raise packet.exception
clickhouse_driver.errors.ServerException: Code: 60.
DB::Exception: Table default.migrations_dist doesn't exist. Stack trace:

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0xe40a075 in /usr/bin/clickhouse
1. ? @ 0x8b88504 in /usr/bin/clickhouse
2. DB::DatabaseCatalog::getTableImpl(DB::StorageID const&, std::shared_ptr<DB::Context const>, std::optional<DB::Exception>*) const @ 0x131d7b9a in /usr/bin/clickhouse
3. DB::DatabaseCatalog::getTable(DB::StorageID const&, std::shared_ptr<DB::Context const>) const @ 0x131de86a in /usr/bin/clickhouse
4. DB::JoinedTables::getLeftTableStorage() @ 0x13cf7894 in /usr/bin/clickhouse
5. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context> const&, std::optional<DB::Pipe>, std::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::vector<String, std::allocator<String>> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::shared_ptr<DB::PreparedSets>) @ 0x13c0d944 in /usr/bin/clickhouse
6. DB::InterpreterSelectWithUnionQuery::buildCurrentChildInterpreter(std::shared_ptr<DB::IAST> const&, std::vector<String, std::allocator<String>> const&) @ 0x13cb0b02 in /usr/bin/clickhouse
7. DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context>, DB::SelectQueryOptions const&, std::vector<String, std::allocator<String>> const&) @ 0x13cae773 in /usr/bin/clickhouse
8. DB::InterpreterFactory::get(std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::Context>, DB::SelectQueryOptions const&) @ 0x13bc7070 in /usr/bin/clickhouse
9. ? @ 0x13fd0e82 in /usr/bin/clickhouse
10. DB::executeQuery(String const&, std::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x13fcec4d in /usr/bin/clickhouse
11. DB::TCPHandler::runImpl() @ 0x14da5e51 in /usr/bin/clickhouse
12. DB::TCPHandler::run() @ 0x14dbb959 in /usr/bin/clickhouse
13. Poco::Net::TCPServerConnection::start() @ 0x17d2ed14 in /usr/bin/clickhouse
14. Poco::Net::TCPServerDispatcher::run() @ 0x17d2ff3b in /usr/bin/clickhouse
15. Poco::PooledThread::run() @ 0x17ead2e7 in /usr/bin/clickhouse
16. Poco::ThreadImpl::runnableEntry(void*) @ 0x17eaad1d in /usr/bin/clickhouse
17. ? @ 0x7fd5fdda7609 in ?
18. clone @ 0x7fd5fdccc133 in ?


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/migrations.py", line 74, in migrate
    runner.run_all(force=force, group=migration_group)
  File "/usr/src/snuba/snuba/migrations/runner.py", line 179, in run_all
    self._run_migration_impl(migration_key, force=force)
  File "/usr/src/snuba/snuba/migrations/runner.py", line 239, in _run_migration_impl
    migration.forwards(context, dry_run)
  File "/usr/src/snuba/snuba/migrations/migration.py", line 144, in forwards
    update_status(Status.COMPLETED)
  File "/usr/src/snuba/snuba/migrations/runner.py", line 389, in _update_migration_status
    next_version = self._get_next_version(migration_key)
  File "/usr/src/snuba/snuba/migrations/runner.py", line 404, in _get_next_version
    result = self.__connection.execute(
  File "/usr/src/snuba/snuba/clickhouse/native.py", line 268, in execute
    raise ClickhouseError(e.message, code=e.code) from e
snuba.clickhouse.errors.ClickhouseError: DB::Exception: Table default.migrations_dist doesn't exist. Stack trace:

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0xe40a075 in /usr/bin/clickhouse
1. ? @ 0x8b88504 in /usr/bin/clickhouse
2. DB::DatabaseCatalog::getTableImpl(DB::StorageID const&, std::shared_ptr<DB::Context const>, std::optional<DB::Exception>*) const @ 0x131d7b9a in /usr/bin/clickhouse
3. DB::DatabaseCatalog::getTable(DB::StorageID const&, std::shared_ptr<DB::Context const>) const @ 0x131de86a in /usr/bin/clickhouse
4. DB::JoinedTables::getLeftTableStorage() @ 0x13cf7894 in /usr/bin/clickhouse
5. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context> const&, std::optional<DB::Pipe>, std::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::vector<String, std::allocator<String>> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::shared_ptr<DB::PreparedSets>) @ 0x13c0d944 in /usr/bin/clickhouse
6. DB::InterpreterSelectWithUnionQuery::buildCurrentChildInterpreter(std::shared_ptr<DB::IAST> const&, std::vector<String, std::allocator<String>> const&) @ 0x13cb0b02 in /usr/bin/clickhouse
7. DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context>, DB::SelectQueryOptions const&, std::vector<String, std::allocator<String>> const&) @ 0x13cae773 in /usr/bin/clickhouse
8. DB::InterpreterFactory::get(std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::Context>, DB::SelectQueryOptions const&) @ 0x13bc7070 in /usr/bin/clickhouse
9. ? @ 0x13fd0e82 in /usr/bin/clickhouse
10. DB::executeQuery(String const&, std::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x13fcec4d in /usr/bin/clickhouse
11. DB::TCPHandler::runImpl() @ 0x14da5e51 in /usr/bin/clickhouse
12. DB::TCPHandler::run() @ 0x14dbb959 in /usr/bin/clickhouse
13. Poco::Net::TCPServerConnection::start() @ 0x17d2ed14 in /usr/bin/clickhouse
14. Poco::Net::TCPServerDispatcher::run() @ 0x17d2ff3b in /usr/bin/clickhouse
15. Poco::PooledThread::run() @ 0x17ead2e7 in /usr/bin/clickhouse
16. Poco::ThreadImpl::runnableEntry(void*) @ 0x17eaad1d in /usr/bin/clickhouse
17. ? @ 0x7fd5fdda7609 in ?
18. clone @ 0x7fd5fdccc133 in ?
```

**Comment by ggolin** [comment]
I can repro this on an empty database all the way to v22.

**Comment by ggolin** [comment]
Snuba migration is broken in chart versions since at least 16. Clean install will not complete successfully. Installing v15 first makes this issue go away for later chart versions, _until v18_.

**Comment by Robing** [comment]
@ggolin after Sentry chart 28, how to handle this issue?

**Comment by duclm2609** [comment]
I've got the same issue on a fresh install of Chart version 24.4.1. Can someone please look into the issue? This is my very first time working with Sentry self-hosted so I have no idea what to check. Google the issue does not help. Thanks.
