### ISSUE TITLE
snuba-metrics-consumer doesn't work after upgrade to 23.10.0

### ISSUE THREAD

**Issue by adonskoy** [getsentry/snuba#4897]
### Environment

Self-hosted

### Steps to Reproduce

1. Upgrade sentry installation from 23.9.1 to 23.10.0

### Expected Result
All snuba consumers work well as always

### Actual Result

snuba-metrics-consumer couldn't write data to Clickhouse Distributed table

#### Logs:
```
2023-10-19 15:14:48,401 Initializing Snuba...
2023-10-19 15:14:51,319 Snuba initialization took 2.917879468994215s
2023-10-19 15:14:51,335 Consumer Starting
2023-10-19 15:14:51,335 Checking Clickhouse connections
2023-10-19 15:14:51,357 librdkafka log level: 6
2023-10-19 15:14:51,373 New partitions assigned: {Partition(topic=Topic(name='snuba-metrics'), index=0): 114576}
2023-10-19 15:15:02,876 Caught exception, shutting down...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 291, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 372, in _run_once
    self.__processing_strategy.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/guard.py", line 101, in poll
    self.__inner_strategy.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/run_task.py", line 55, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/guard.py", line 37, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/reduce.py", line 153, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/run_task_in_threads.py", line 107, in poll
    result = future.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/snuba/snuba/consumers/strategy_factory.py", line 124, in flush_batch
    message.payload.close()
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 314, in close
    self.__insert_batch_writer.close()
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 160, in close
    self.__writer.write(
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 347, in write
    batch.join(timeout=batch_join_timeout)
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 274, in join
    raise ClickhouseWriterError(message, code=code, row=row)
snuba.clickhouse.errors.ClickhouseWriterError: Method write is not supported by storage Distributed with more than one shard and no sharding key provided (version 21.8.13.6 (official build))
2023-10-19 15:15:02,880 Closing <arroyo.backends.kafka.consumer.KafkaConsumer object at 0x7fe4b578ed60>...
2023-10-19 15:15:02,880 Partitions to revoke: [Partition(topic=Topic(name='snuba-metrics'), index=0)]
2023-10-19 15:15:02,880 Partition revocation complete.
2023-10-19 15:15:02,881 Processor terminated
```

#### Additional info:
- clickhouse  version: `21.8.13.6`
- command: `snuba consumer --storage metrics_raw --consumer-group snuba-metrics-consumers --auto-offset-reset latest --max-batch-time-ms 750 --no-strict-offset-reset`

**Comment by adonskoy** [comment]
None of the metrics tables have a sharding key. However, it is not clear why the problem appeared only at 23.10; the last time the metrics migrations were changed was 9 months ago.

<img width="554" alt="image" src="https://github.com/getsentry/snuba/assets/13225811/f8daa1f4-36c2-442d-b5a0-d210515e7f09">

**Comment by nikhars** [comment]
Hi

Thank you for reporting the issue. It is a bug in the migration code right now. We will work on making the right fix for this.

Thanks.
Nikhar

**Comment by brogger71** [comment]
Hi @nikhars,

Any idea, when the fix will be available?

Thanks,
Michael

**Comment by taxilian** [comment]
Does anyone know how to manually apply whatever change is needed for this migration? that would let those of us affected resolve it in the mean time

**Comment by onewland** [comment]
The right solution that will allow for no downtime in our (our referring to Sentry the company) SaaS installation is:

1. migration 1: create a v3 distributed table for metrics_raw, with essentially the same schema but setting timeseries_id to be the sharding key
1. config change: change the metrics_raw storage to point to the v3 distributed table
1. (cleanup) migration 2: delete the v2 distributed table

This isn't high-priority for us because we run this storage on a single shard in our largest production region (so we don't hit this error condition) and have not encountered any performance issues that would justify sharding out.

We would welcome external PRs to support this, though, and you're also free to run out-of-band SQL on your installations if you want to just drop and recreate the table with the sharding key set to that column.

**Comment by shcherbak** [comment]
this fixed for me:
```
DROP table default.metrics_raw_v2_dist ON CLUSTER 'sentry-clickhouse' SYNC;
CREATE TABLE default.metrics_raw_v2_dist ON CLUSTER 'sentry-clickhouse'
(
    `use_case_id` LowCardinality(String),
    `org_id` UInt64,
    `project_id` UInt64,
    `metric_id` UInt64,
    `timestamp` DateTime,
    `tags.key` Array(UInt64),
    `tags.value` Array(UInt64),
    `metric_type` LowCardinality(String),
    `set_values` Array(UInt64),
    `count_value` Float64,
    `distribution_values` Array(Float64),
    `materialization_version` UInt8,
    `retention_days` UInt16,
    `partition` UInt16,
    `offset` UInt64,
    `timeseries_id` UInt32
)
ENGINE = Distributed('sentry-clickhouse', 'default', 'metrics_raw_v2_local', sipHash64('timeseries_id'));
```

**Comment by tomwganem** [comment]
@shcherbak Thanks. That worked for me too.

**Comment by tomwganem** [comment]
For others, because I've never interacted with clickhouse before:
```sh
$ kubectl exec -it sentry-clickhouse-0 -- bash
root@sentry-clickhouse-0:/# clickhouse-client -h sentry-clickhouse
ClickHouse client version 21.8.13.6 (official build).
Connecting to sentry-clickhouse:9000 as user default.
Connected to ClickHouse server version 21.8.13 revision 54449.

sentry-clickhouse :) SHOW TABLES;

SHOW TABLES

Query id: 00a56a30-1f3a-47bc-9017-0d7b0e753e32

┌─name───────────────────────────────────────────┐
│ discover_dist                                  │
│ discover_local                                 │
│ errors_dist                                    │
│ errors_dist_ro                                 │
│ errors_local                                   │
│ functions_local                                │
│ functions_mv_dist                              │
│ functions_mv_local                             │
│ functions_raw_dist                             │
│ functions_raw_local                            │
│ generic_metric_counters_aggregated_dist        │
│ generic_metric_counters_aggregated_local       │
│ generic_metric_counters_aggregation_mv         │
│ generic_metric_counters_aggregation_mv_v2      │
│ generic_metric_counters_raw_dist               │
│ generic_metric_counters_raw_local              │
│ generic_metric_distributions_aggregated_dist   │
│ generic_metric_distributions_aggregated_local  │
│ generic_metric_distributions_aggregation_mv    │
│ generic_metric_distributions_aggregation_mv_v2 │
│ generic_metric_distributions_raw_dist          │
│ generic_metric_distributions_raw_local         │
│ generic_metric_gauges_aggregated_dist          │
│ generic_metric_gauges_aggregated_local         │
│ generic_metric_gauges_aggregation_mv           │
│ generic_metric_gauges_raw_dist                 │
│ generic_metric_gauges_raw_local                │
│ generic_metric_sets_aggregated_dist            │
│ generic_metric_sets_aggregation_mv             │
│ generic_metric_sets_aggregation_mv_v2          │
│ generic_metric_sets_local                      │
│ generic_metric_sets_raw_dist                   │
│ generic_metric_sets_raw_local                  │
│ group_attributes_dist                          │
│ group_attributes_local                         │
│ groupassignee_dist                             │
│ groupassignee_local                            │
│ groupedmessage_dist                            │
│ groupedmessage_local                           │
│ metrics_counters_polymorphic_mv_v4_local       │
│ metrics_counters_v2_dist                       │
│ metrics_counters_v2_local                      │
│ metrics_distributions_polymorphic_mv_v4_local  │
│ metrics_distributions_v2_dist                  │
│ metrics_distributions_v2_local                 │
│ metrics_raw_v2_dist                            │
│ metrics_raw_v2_local                           │
│ metrics_sets_polymorphic_mv_v4_local           │
│ metrics_sets_v2_dist                           │
│ metrics_sets_v2_local                          │
│ migrations_dist                                │
│ migrations_local                               │
│ outcomes_hourly_dist                           │
│ outcomes_hourly_local                          │
│ outcomes_mv_hourly_local                       │
│ outcomes_raw_dist                              │
│ outcomes_raw_local                             │
│ profiles_dist                                  │
│ profiles_local                                 │
│ querylog_dist                                  │
│ querylog_local                                 │
│ replays_dist                                   │
│ replays_local                                  │
│ search_issues_dist                             │
│ search_issues_dist_v2                          │
│ search_issues_local                            │
│ search_issues_local_v2                         │
│ sessions_hourly_dist                           │
│ sessions_hourly_local                          │
│ sessions_hourly_mv_local                       │
│ sessions_raw_dist                              │
│ sessions_raw_local                             │
│ spans_dist                                     │
│ spans_local                                    │
│ test_migration_dist                            │
│ test_migration_local                           │
│ transactions_dist                              │
│ transactions_local                             │
└────────────────────────────────────────────────┘

78 rows in set. Elapsed: 0.012 sec.

sentry-clickhouse :) DESCRIBE TABLE default.metrics_raw_v2_dist;

DESCRIBE TABLE  default.metrics_raw_v2_dist

Query id: 28daccfc-d3dc-4caa-8adc-3d2a08abf20d

┌─name────────────────────┬─type───────────────────┬─default_type─┬─default_expression─┬─comment─┬─codec_expression─┬─ttl_expression─┐
│ use_case_id             │ LowCardinality(String) │              │                    │         │                  │                │
│ org_id                  │ UInt64                 │              │                    │         │                  │                │
│ project_id              │ UInt64                 │              │                    │         │                  │                │
│ metric_id               │ UInt64                 │              │                    │         │                  │                │
│ timestamp               │ DateTime               │              │                    │         │                  │                │
│ tags.key                │ Array(UInt64)          │              │                    │         │                  │                │
│ tags.value              │ Array(UInt64)          │              │                    │         │                  │                │
│ metric_type             │ LowCardinality(String) │              │                    │         │                  │                │
│ set_values              │ Array(UInt64)          │              │                    │         │                  │                │
│ count_value             │ Float64                │              │                    │         │                  │                │
│ distribution_values     │ Array(Float64)         │              │                    │         │                  │                │
│ materialization_version │ UInt8                  │              │                    │         │                  │                │
│ retention_days          │ UInt16                 │              │                    │         │                  │                │
│ partition               │ UInt16                 │              │                    │         │                  │                │
│ offset                  │ UInt64                 │              │                    │         │                  │                │
│ timeseries_id           │ UInt32                 │              │                    │         │                  │                │
└─────────────────────────┴────────────────────────┴──────────────┴────────────────────┴─────────┴──────────────────┴────────────────┘

16 rows in set. Elapsed: 0.004 sec.

sentry-clickhouse :) SELECT COUNT(*) FROM default.metrics_raw_v2_dist;

SELECT COUNT(*)
FROM default.metrics_raw_v2_dist

Query id: 1d5e2a59-4f88-4274-80a1-828d4d0acbc1

┌─count()─┐
│       0 │
└─────────┘

1 rows in set. Elapsed: 0.025 sec.

sentry-clickhouse :) DROP table default.metrics_raw_v2_dist ON CLUSTER 'sentry-clickhouse' SYNC;

DROP TABLE default.metrics_raw_v2_dist ON CLUSTER `sentry-clickhouse` NO DELAY

Query id: 83f1a44a-15dd-4491-97e5-b2dd16e31676

┌─host────────────────────────────────────────────────────────────────────┬─port─┬─status─┬─error─┬─num_hosts_remaining─┬─num_hosts_active─┐
│ sentry-clickhouse-2.sentry-clickhouse-headless.sentry.svc.cluster.local │ 9000 │      0 │       │                   2 │                0 │
│ sentry-clickhouse-1.sentry-clickhouse-headless.sentry.svc.cluster.local │ 9000 │      0 │       │                   1 │                0 │
└─────────────────────────────────────────────────────────────────────────┴──────┴────────┴───────┴─────────────────────┴──────────────────┘
┌─host────────────────────────────────────────────────────────────────────┬─port─┬─status─┬─error─┬─num_hosts_remaining─┬─num_hosts_active─┐
│ sentry-clickhouse-0.sentry-clickhouse-headless.sentry.svc.cluster.local │ 9000 │      0 │       │                   0 │                0 │
└─────────────────────────────────────────────────────────────────────────┴──────┴────────┴───────┴─────────────────────┴──────────────────┘

3 rows in set. Elapsed: 0.203 sec.

sentry-clickhouse :) CREATE TABLE default.metrics_raw_v2_dist ON CLUSTER 'sentry-clickhouse'
:-] (
:-]     `use_case_id` LowCardinality(String),
:-]     `org_id` UInt64,
:-]     `project_id` UInt64,
:-]     `metric_id` UInt64,
:-]     `timestamp` DateTime,
:-]     `tags.key` Array(UInt64),
:-]     `tags.value` Array(UInt64),
:-]     `metric_type` LowCardinality(String),
:-]     `set_values` Array(UInt64),
:-]     `count_value` Float64,
:-]     `distribution_values` Array(Float64),
:-]     `materialization_version` UInt8,
:-]     `retention_days` UInt16,
:-]     `partition` UInt16,
:-]     `offset` UInt64,
:-]     `timeseries_id` UInt32
:-] )
:-] ENGINE = Distributed('sentry-clickhouse', 'default', 'metrics_raw_v2_local', sipHash64('timeseries_id'));

CREATE TABLE default.metrics_raw_v2_dist ON CLUSTER `sentry-clickhouse`
(
    `use_case_id` LowCardinality(String),
    `org_id` UInt64,
    `project_id` UInt64,
    `metric_id` UInt64,
    `timestamp` DateTime,
    `tags.key` Array(UInt64),
    `tags.value` Array(UInt64),
    `metric_type` LowCardinality(String),
    `set_values` Array(UInt64),
    `count_value` Float64,
    `distribution_values` Array(Float64),
    `materialization_version` UInt8,
    `retention_days` UInt16,
    `partition` UInt16,
    `offset` UInt64,
    `timeseries_id` UInt32
)
ENGINE = Distributed('sentry-clickhouse', 'default', 'metrics_raw_v2_local', sipHash64('timeseries_id'))

Query id: 011e2e89-faea-4e14-88d7-68c7679c1293

┌─host────────────────────────────────────────────────────────────────────┬─port─┬─status─┬─error─┬─num_hosts_remaining─┬─num_hosts_active─┐
│ sentry-clickhouse-2.sentry-clickhouse-headless.sentry.svc.cluster.local │ 9000 │      0 │       │                   2 │                0 │
│ sentry-clickhouse-1.sentry-clickhouse-headless.sentry.svc.cluster.local │ 9000 │      0 │       │                   1 │                0 │
│ sentry-clickhouse-0.sentry-clickhouse-headless.sentry.svc.cluster.local │ 9000 │      0 │       │                   0 │                0 │
└─────────────────────────────────────────────────────────────────────────┴──────┴────────┴───────┴─────────────────────┴──────────────────┘

3 rows in set. Elapsed: 0.253 sec.
```

**Comment by hubertdeng123** [comment]
Thanks for submitting this solution. Please be aware that it is difficult to support all use cases of self-hosted in the wild. The official version of self-hosted that we support does not support clickhouse sharding

**Comment by prasadkris** [comment]
Unfortunately, the above-mentioned procedure (https://github.com/getsentry/snuba/issues/4897#issuecomment-1909077805) didn't work for me. I get the error below from the metrics consumer pod, which crash-loops after recreating the table. Any idea on how to fix this? Thanks

```
snuba.clickhouse.errors.ClickhouseWriterError: Cannot parse input: expected '[' before: 'null,"count_value":1.0,"distribution_values":null,"materialization_version":4,"timeseries_id":1577390759,"partition":0,"offset":0}{"use_case_id":"sessions","org': (while reading the value of key set_values): (at row 1)
2024-05-28 04:48:45,982 Closing <arroyo.backends.kafka.consumer.KafkaConsumer object at 0x7f2f70a2cbd0>...
2024-05-28 04:48:45,983 Partitions to revoke: [Partition(topic=Topic(name='snuba-metrics'), index=0)]
2024-05-28 04:48:45,983 Partition revocation complete.
2024-05-28 04:48:45,986 Processor terminated
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/snuba/snuba/cli/consumer.py", line 284, in consumer
    consumer.run()
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/processor.py", line 321, in run
    self._run_once()
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/processor.py", line 395, in _run_once
    self.__processing_strategy.poll()
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/strategies/guard.py", line 101, in poll
    self.__inner_strategy.poll()
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/strategies/run_task.py", line 55, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/strategies/guard.py", line 37, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/strategies/reduce.py", line 101, in poll
    self.__buffer_step.poll()
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/strategies/buffer.py", line 169, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/strategies/run_task_in_threads.py", line 107, in poll
    result = future.result()
             ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/snuba/snuba/consumers/strategy_factory.py", line 137, in flush_batch
    message.payload.close()
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 300, in close
    self.__insert_batch_writer.close()
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 136, in close
    self.__writer.write(
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 359, in write
    batch.join(timeout=batch_join_timeout)
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 282, in join
    raise ClickhouseWriterError(message, code=code, row=row)
snuba.clickhouse.errors.ClickhouseWriterError: Cannot parse input: expected '[' before: 'null,"count_value":1.0,"distribution_values":null,"materialization_version":4,"timeseries_id":1577390759,"partition":0,"offset":0}{"use_case_id":"sessions","org': (while reading the value of key set_values): (at row 1)```

**Comment by JustDoItSascha** [comment]
We have the same issue like the OP, on a 6 days old installation with the newest helm chart 23.1.0 and app version 24.5.0. It did run for a couple of days and then we have this error. We didn't upgrade anything or touched anything.

There is no clickhouse sharding enabled, it's just the completely default helm chart installation. It's only 6 DAYS old. :(

How can this happen? As much as I love Sentry as a Software, I hate the deployment process and the helm chart. It's just ridiculous how often the installation fails. It's a nightmare to update the chart... So much that sometimes only a completely reinstall helps. From all helm charts I ever installed, the sentry one is the worst. It's like somebody is actively trying to sabotage the self hosting.

I'm very sorry if I may have hurt someones feeling, but I'm just frustrated like I was never before from installing a software :(.

**Comment by dpunkturban** [comment]
We have the same problem with a fresh installation.

Chart.yaml
```
apiVersion: v2
dependencies:
  - name: sentry
    repository: https://sentry-kubernetes.github.io/charts
    version: 23.12.1
```

Application version
24.5.1


Error:
```
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/processor.py", line 396, in _run_once
    self.__processing_strategy.poll()
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/strategies/healthcheck.py", line 32, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/strategies/guard.py", line 101, in poll
    self.__inner_strategy.poll()
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/strategies/run_task.py", line 55, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/strategies/guard.py", line 37, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/strategies/reduce.py", line 101, in poll
    self.__buffer_step.poll()
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/strategies/buffer.py", line 169, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/strategies/run_task_in_threads.py", line 107, in poll
    result = future.result()
             ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/snuba/snuba/consumers/strategy_factory.py", line 135, in flush_batch
    message.payload.close()
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 300, in close
    self.__insert_batch_writer.close()
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 136, in close
    self.__writer.write(
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 359, in write
    batch.join(timeout=batch_join_timeout)
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 282, in join
    raise ClickhouseWriterError(message, code=code, row=row)
snuba.clickhouse.errors.ClickhouseWriterError: Method write is not supported by storage Distributed with more than one shard and no sharding key provided (version 21.8.13.6 (official build))
2024-08-08 08:10:56,846 Closing <arroyo.backends.kafka.consumer.KafkaConsumer object at 0x7f8640b9bed0>...
2024-08-08 08:10:56,846 Partitions to revoke: [Partition(topic=Topic(name='snuba-metrics'), index=0)]
2024-08-08 08:10:56,846 Partition revocation complete.
2024-08-08 08:10:56,848 Processor terminated
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/snuba/snuba/cli/consumer.py", line 279, in consumer
    consumer.run()
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/processor.py", line 322, in run
    self._run_once()
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/processor.py", line 396, in _run_once
    self.__processing_strategy.poll()
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/strategies/healthcheck.py", line 32, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/strategies/guard.py", line 101, in poll
    self.__inner_strategy.poll()
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/strategies/run_task.py", line 55, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/strategies/guard.py", line 37, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/strategies/reduce.py", line 101, in poll
    self.__buffer_step.poll()
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/strategies/buffer.py", line 169, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/strategies/run_task_in_threads.py", line 107, in poll
    result = future.result()
             ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/snuba/snuba/consumers/strategy_factory.py", line 135, in flush_batch
    message.payload.close()
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 300, in close
    self.__insert_batch_writer.close()
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 136, in close
    self.__writer.write(
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 359, in write
    batch.join(timeout=batch_join_timeout)
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 282, in join
    raise ClickhouseWriterError(message, code=code, row=row)
snuba.clickhouse.errors.ClickhouseWriterError: Method write is not supported by storage Distributed with more than one shard and no sharding key provided (version 21.8.13.6 (official build))
Stream closed EOF for sentry/sentry-snuba-metrics-consumer-78965848ff-lxzdq (sentry-snuba)

```

**Comment by gersmann** [comment]
My suggestion to anyone, who doesn't need Sentry to be super-HA - just run it via the official docker compose scripts (from getsentry/self-hosted). This solution (though not designed for HA) is for sure much more stable for us. The only adaption we've had to make is to increase the scale factor of workers for higher throughput.

**Comment by seborys40** [comment]
@gersmann , that's good to hear. Are you running it on k8s via helm chart ? I'm doing as such and closely aligning all settings how they are in self-hosted.
