### ISSUE TITLE
Clickhouse writer error: Method write is not supported by storage Distributed with more than one shard and no sharding key provided in Sentry 23.10.1

### ISSUE THREAD

**Issue by kfkawalec** [getsentry/snuba#4921]
### Self-Hosted Version

23.10.1

### CPU Architecture

x86_64

### Docker Version

Kubernetes 

### Docker Compose Version

v1.26.8+rke2r1

### Steps to Reproduce

Upgrade clean Helm version from 23.8.1 to 23.10.1

### Expected Result

Pod without restarting.

### Actual Result

snuba-replays-consumer restart with errror:
```
2023-10-24 19:45:13,638 Initializing Snuba...
2023-10-24T21:45:17.966409460+02:00 2023-10-24 19:45:17,966 Snuba initialization took 4.328181455959566s
2023-10-24T21:45:17.991066278+02:00 2023-10-24 19:45:17,990 Consumer Starting
2023-10-24T21:45:17.991340319+02:00 2023-10-24 19:45:17,991 Checking Clickhouse connections
2023-10-24 19:45:18,012 librdkafka log level: 6
2023-10-24T21:45:21.060872881+02:00 2023-10-24 19:45:21,060 New partitions assigned: {Partition(topic=Topic(name='snuba-metrics'), index=0): 0}
2023-10-24T21:45:23.379180938+02:00 2023-10-24 19:45:23,375 Caught exception, shutting down...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 291, in run
    self._run_once()
2023-10-24T21:45:23.379268592+02:00   File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 372, in _run_once
2023-10-24T21:45:23.379276005+02:00     self.__processing_strategy.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/guard.py", line 101, in poll
    self.__inner_strategy.poll()
2023-10-24T21:45:23.379299336+02:00   File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/run_task.py", line 55, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/guard.py", line 37, in poll
    self.__next_step.poll()
2023-10-24T21:45:23.379335748+02:00   File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/reduce.py", line 153, in poll
2023-10-24T21:45:23.379344308+02:00     self.__next_step.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/run_task_in_threads.py", line 107, in poll
    result = future.result()
2023-10-24T21:45:23.379375784+02:00   File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
2023-10-24T21:45:23.379436700+02:00   File "/usr/src/snuba/snuba/consumers/strategy_factory.py", line 124, in flush_batch
2023-10-24T21:45:23.379458928+02:00     message.payload.close()
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 324, in close
    self.__insert_batch_writer.close()
2023-10-24T21:45:23.379484264+02:00   File "/usr/src/snuba/snuba/consumers/consumer.py", line 160, in close
    self.__writer.write(
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 347, in write
2023-10-24T21:45:23.379507110+02:00     batch.join(timeout=batch_join_timeout)
2023-10-24T21:45:23.379515350+02:00   File "/usr/src/snuba/snuba/clickhouse/http.py", line 274, in join
    raise ClickhouseWriterError(message, code=code, row=row)
snuba.clickhouse.errors.ClickhouseWriterError: Method write is not supported by storage Distributed with more than one shard and no sharding key provided (version 21.8.13.6 (official build))
2023-10-24T21:45:23.384093198+02:00 2023-10-24 19:45:23,383 Closing <arroyo.backends.kafka.consumer.KafkaConsumer object at 0x7f7fd2dc3eb0>...
2023-10-24 19:45:23,384 Partitions to revoke: [Partition(topic=Topic(name='snuba-metrics'), index=0)]
2023-10-24 19:45:23,384 Partition revocation complete.
2023-10-24T21:45:23.431604082+02:00 2023-10-24 19:45:23,431 Processor terminated
2023-10-24T21:45:23.444187470+02:00 Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
2023-10-24T21:45:23.444261625+02:00     sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
2023-10-24T21:45:23.444288823+02:00   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
2023-10-24T21:45:23.444304903+02:00   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
2023-10-24T21:45:23.444314088+02:00     return _process_result(sub_ctx.command.invoke(sub_ctx))
2023-10-24T21:45:23.444322402+02:00   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
2023-10-24T21:45:23.444329820+02:00     return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
2023-10-24T21:45:23.444344188+02:00     return __callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/consumer.py", line 279, in consumer
    consumer.run()
2023-10-24T21:45:23.444367534+02:00   File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 291, in run
2023-10-24T21:45:23.444374873+02:00     self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 372, in _run_once
    self.__processing_strategy.poll()
2023-10-24T21:45:23.444397013+02:00   File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/guard.py", line 101, in poll
2023-10-24T21:45:23.444404159+02:00     self.__inner_strategy.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/run_task.py", line 55, in poll
2023-10-24T21:45:23.444418457+02:00     self.__next_step.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/guard.py", line 37, in poll
    self.__next_step.poll()
2023-10-24T21:45:23.444439942+02:00   File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/reduce.py", line 153, in poll
2023-10-24T21:45:23.444447322+02:00     self.__next_step.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/run_task_in_threads.py", line 107, in poll
    result = future.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 437, in result
2023-10-24T21:45:23.444477267+02:00     return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
2023-10-24T21:45:23.444524359+02:00   File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
2023-10-24T21:45:23.444542106+02:00   File "/usr/src/snuba/snuba/consumers/strategy_factory.py", line 124, in flush_batch
2023-10-24T21:45:23.444550149+02:00     message.payload.close()
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 324, in close
    self.__insert_batch_writer.close()
2023-10-24T21:45:23.444572092+02:00   File "/usr/src/snuba/snuba/consumers/consumer.py", line 160, in close
    self.__writer.write(
2023-10-24T21:45:23.444589773+02:00   File "/usr/src/snuba/snuba/clickhouse/http.py", line 347, in write
    batch.join(timeout=batch_join_timeout)
2023-10-24T21:45:23.444604404+02:00   File "/usr/src/snuba/snuba/clickhouse/http.py", line 274, in join
    raise ClickhouseWriterError(message, code=code, row=row)
snuba.clickhouse.errors.ClickhouseWriterError: Method write is not supported by storage Distributed with more than one shard and no sharding key provided (version 21.8.13.6 (official build))
```

**Comment by onewland** [comment]
This is a dupe of https://github.com/getsentry/snuba/issues/4897
