### ISSUE TITLE
snuba-consumer: TypeError: unsupported type for timedelta days component: str

### ISSUE THREAD

**Issue by larsnystrom-client** [getsentry/snuba#4925]
### Environment

23.10.1

### Steps to Reproduce

This is just a duplicate ticket of https://github.com/getsentry/snuba/issues/2780 since it is still affecting us. I posted a fix there, which would be nice if you could incorporate into the codebase so that I don't have to do it manually after each upgrade. Without my fix the snuba-consumer keeps on dying, and sending a new event to Sentry, which it then can't consume because snuba-consumer keeps dying, which causes the `redis` service to use up all RAM on the server, which in turn causes cascading failures of everything else.

### Expected Result

No TypeErrors.

### Actual Result

    sentry-self-hosted-snuba-consumer-1  | 2023-10-25 08:26:56,871 unsupported type for timedelta days component: str
    sentry-self-hosted-snuba-consumer-1  | Traceback (most recent call last):
    sentry-self-hosted-snuba-consumer-1  |   File "/usr/src/snuba/snuba/consumers/consumer.py", line 581, in process_message
    sentry-self-hosted-snuba-consumer-1  |     result = processor.process_message(
    sentry-self-hosted-snuba-consumer-1  |   File "/usr/src/snuba/snuba/datasets/processors/errors_processor.py", line 76, in process_message
    sentry-self-hosted-snuba-consumer-1  |     row = self.process_insert(cast(InsertEvent, event), metadata)
    sentry-self-hosted-snuba-consumer-1  |   File "/usr/src/snuba/snuba/datasets/processors/errors_processor.py", line 99, in process_insert
    sentry-self-hosted-snuba-consumer-1  |     processed["retention_days"] = enforce_retention(
    sentry-self-hosted-snuba-consumer-1  |   File "/usr/src/snuba/snuba/datasets/events_format.py", line 125, in enforce_retention
    sentry-self-hosted-snuba-consumer-1  |     datetime.utcnow() - timedelta(days=retention_days)
    sentry-self-hosted-snuba-consumer-1  | TypeError: unsupported type for timedelta days component: str
    sentry-self-hosted-snuba-consumer-1  | 2023-10-25 08:26:56,874 (Partition(topic=Topic(name='events'), index=0), 572704)
    sentry-self-hosted-snuba-consumer-1  | Traceback (most recent call last):
    sentry-self-hosted-snuba-consumer-1  |   File "/usr/src/snuba/snuba/consumers/consumer.py", line 581, in process_message
    sentry-self-hosted-snuba-consumer-1  |     result = processor.process_message(
    sentry-self-hosted-snuba-consumer-1  |   File "/usr/src/snuba/snuba/datasets/processors/errors_processor.py", line 76, in process_message
    sentry-self-hosted-snuba-consumer-1  |     row = self.process_insert(cast(InsertEvent, event), metadata)
    sentry-self-hosted-snuba-consumer-1  |   File "/usr/src/snuba/snuba/datasets/processors/errors_processor.py", line 99, in process_insert
    sentry-self-hosted-snuba-consumer-1  |     processed["retention_days"] = enforce_retention(
    sentry-self-hosted-snuba-consumer-1  |   File "/usr/src/snuba/snuba/datasets/events_format.py", line 125, in enforce_retention
    sentry-self-hosted-snuba-consumer-1  |     datetime.utcnow() - timedelta(days=retention_days)
    sentry-self-hosted-snuba-consumer-1  | TypeError: unsupported type for timedelta days component: str
    sentry-self-hosted-snuba-consumer-1  |
    sentry-self-hosted-snuba-consumer-1  | The above exception was the direct cause of the following exception:
    sentry-self-hosted-snuba-consumer-1  |
    sentry-self-hosted-snuba-consumer-1  | Traceback (most recent call last):
    sentry-self-hosted-snuba-consumer-1  |   File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 386, in _run_once
    sentry-self-hosted-snuba-consumer-1  |     self.__processing_strategy.submit(message)
    sentry-self-hosted-snuba-consumer-1  |   File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/guard.py", line 85, in submit
    sentry-self-hosted-snuba-consumer-1  |     raise e
    sentry-self-hosted-snuba-consumer-1  |   File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/guard.py", line 82, in submit
    sentry-self-hosted-snuba-consumer-1  |     self.__inner_strategy.submit(message)
    sentry-self-hosted-snuba-consumer-1  |   File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/run_task.py", line 50, in submit
    sentry-self-hosted-snuba-consumer-1  |     result = self.__function(cast(Message[TStrategyPayload], message))
    sentry-self-hosted-snuba-consumer-1  |   File "/usr/src/snuba/snuba/consumers/consumer.py", line 601, in process_message
    sentry-self-hosted-snuba-consumer-1  |     raise InvalidMessage(value.partition, value.offset) from err
    sentry-self-hosted-snuba-consumer-1  | arroyo.dlq.InvalidMessage: (Partition(topic=Topic(name='events'), index=0), 572704)

**Comment by larsnystrom-client** [comment]
I'm sorry, it appears this was a configuration error on my end. I replaced `sentry/sentry.conf.py` with `sentry/sentry.conf.example.py` and the problem went away.
