### ISSUE TITLE
consumer_config.replacements_topic.is_none()

### ISSUE THREAD

**Issue by hd-deman** [getsentry/snuba#5427]
### Environment

snuba 24.1.0

### Steps to Reproduce

I'm trying to run rust-consumer like this:

```bash
snuba
rust-consumer
--storage
errors
--auto-offset-reset
earliest
--max-batch-time-ms
750
--consumer-group
snuba-consumers
```

### Actual Result

but I get this error:

```
2024-01-19 09:10:15,206 Initializing Snuba...
2024-01-19 09:10:17,246 Snuba initialization took 2.040593229998194s
thread '<unnamed>' panicked at src/consumer.rs:83:5:
assertion failed: consumer_config.replacements_topic.is_none()
stack backtrace:
{"timestamp":"2024-01-19T09:10:17.254752Z","level":"INFO","fields":{"message":"Starting Rust consumer","consumer_config":"ConsumerConfig { storages: [StorageConfig { name: \"errors\", clickhouse_table_name: \"errors_dist\", clickhouse_cluster: ClickhouseConfig { host: \"sentry-clickhouse\", port: 9000, http_port: 8123, user: \"default\", password: \"\", database: \"default\" }, message_processor: MessageProcessorConfig { python_class_name: \"ErrorsProcessor\", python_module: \"snuba.datasets.processors.errors_processor\" } }], raw_topic: TopicConfig { physical_topic_name: \"events\", logical_topic_name: \"events\", broker_config: {\"queued.max.messages.kbytes\": \"10000\", \"queued.min.messages\": \"10000\", \"security.protocol\": \"plaintext\", \"bootstrap.servers\": \"redpanda-0.redpanda:9093,redpanda-1.redpanda:9093,redpanda-2.redpanda:9093\"} }, commit_log_topic: Some(TopicConfig { physical_topic_name: \"snuba-commit-log\", logical_topic_name: \"snuba-commit-log\", broker_config: {\"bootstrap.servers\": \"redpanda-0.redpanda:9093,redpanda-1.redpanda:9093,redpanda-2.redpanda:9093\", \"security.protocol\": \"plaintext\"} }), replacements_topic: Some(TopicConfig { physical_topic_name: \"event-replacements\", logical_topic_name: \"event-replacements\", broker_config: {\"bootstrap.servers\": \"redpanda-0.redpanda:9093,redpanda-1.redpanda:9093,redpanda-2.redpanda:9093\", \"security.protocol\": \"plaintext\"} }), dlq_topic: None, max_batch_size: 50000, max_batch_time_ms: 750, env: EnvConfig { sentry_dsn: None, dogstatsd_host: None, dogstatsd_port: None, default_retention_days: 90, lower_retention_days: 30, valid_retention_days: {30, 90} } }"},"target":"rust_snuba::consumer"}
   0: rust_begin_unwind
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panicking.rs:127:5
   3: rust_snuba::consumer::consumer_impl
             at ./rust_snuba/src/consumer.rs:83:5
   4: rust_snuba::consumer::consumer::{{closure}}
             at ./rust_snuba/src/consumer.rs:43:9
   5: pyo3::marker::Python::allow_threads
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.18.3/src/marker.rs:473:9
   6: rust_snuba::consumer::consumer
             at ./rust_snuba/src/consumer.rs:42:5
   7: rust_snuba::consumer::_::__pyfunction_consumer
             at ./rust_snuba/src/consumer.rs:26:1
   8: pyo3::impl_::trampoline::fastcall_with_keywords::{{closure}}
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.18.3/src/impl_/trampoline.rs:41:35
   9: pyo3::impl_::trampoline::trampoline_inner::{{closure}}
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.18.3/src/impl_/trampoline.rs:204:54
  10: std::panicking::try::do_call
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:504:40
  11: std::panicking::try
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:468:19
  12: std::panic::catch_unwind
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panic.rs:142:14
  13: pyo3::impl_::trampoline::trampoline_inner
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.18.3/src/impl_/trampoline.rs:204:9
  14: pyo3::impl_::trampoline::fastcall_with_keywords
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.18.3/src/impl_/trampoline.rs:52:1
  15: rust_snuba::consumer::_::<impl rust_snuba::consumer::consumer::MakeDef>::DEF::trampoline
             at ./rust_snuba/src/consumer.rs:26:1
  16: <unknown>
  17: _PyEval_EvalFrameDefault
  18: <unknown>
  19: PyVectorcall_Call
  20: _PyEval_EvalFrameDefault
  21: <unknown>
  22: <unknown>
  23: PyVectorcall_Call
  24: _PyEval_EvalFrameDefault
  25: <unknown>
  26: _PyEval_EvalFrameDefault
  27: <unknown>
  28: _PyEval_EvalFrameDefault
  29: <unknown>
  30: <unknown>
  31: <unknown>
  32: _PyEval_EvalFrameDefault
  33: <unknown>
  34: _PyObject_FastCallDictTstate
  35: _PyObject_Call_Prepend
  36: <unknown>
  37: _PyObject_MakeTpCall
  38: _PyEval_EvalFrameDefault
  39: <unknown>
  40: PyEval_EvalCode
  41: <unknown>
  42: <unknown>
  43: <unknown>
  44: _PyRun_SimpleFileObject
  45: _PyRun_AnyFileObject
  46: Py_RunMain
  47: Py_BytesMain
  48: <unknown>
  49: __libc_start_main
  50: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/rust_consumer.py", line 212, in rust_consumer
    exitcode = rust_snuba.consumer(  # type: ignore
pyo3_runtime.PanicException: assertion failed: consumer_config.replacements_topic.is_none()
Stream closed EOF for sentry/sentry-snuba-consumer-6b7458cf7f-4p8kh (sentry-snuba)
```

What should I specify as `--replacements-topic`?

**Comment by hd-deman** [comment]
same result if I append `--replacements-topic event-replacements`

**Comment by untitaker** [comment]
`--replacements-topic` is not actually supported by rust-consumer, and so any dataset that requires it will not work on it (yet). sorry.

are you running snuba in some custom setup? we haven't moved onprem etc to rust-consumers yet (I hope)

**Comment by hd-deman** [comment]
I just faced with similar issue https://github.com/getsentry/snuba/issues/4596

And tried to switch to rust-consumer, according to [this comment](https://github.com/getsentry/snuba/pull/4988#pullrequestreview-1829739294)

And it's all start working except snuba-consumers

**Comment by untitaker** [comment]
that should not be an issue for consumers. you don't need rust consumers here, you need to increase your batch-size and batch-time so that the insert-rate on clickhouse is approximately 1 insert/s in total (per clickhouse cluster). the metric to watch for is `clickhouse.events.insert_query`
