### ISSUE TITLE
I can't start snuba in develop env

### ISSUE THREAD

**Issue by yujiaao** [getsentry/snuba#6223]
git checkout 24.5.1
source .venv/bin/activate
make develop
snuba api

and it produce error:

```
                                                 4d7410723
⚡ snuba api
2024-08-20 20:57:54,410 Initializing Snuba...
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1651, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1698, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xwx/study/snuba/snuba/cli/__init__.py", line 58, in get_command
    initialize.initialize_snuba()
  File "/Users/xwx/study/snuba/snuba/core/initialize.py", line 41, in initialize_snuba
    _load_storages()
  File "/Users/xwx/study/snuba/snuba/core/initialize.py", line 23, in _load_storages
    initialize_storage_factory()
  File "/Users/xwx/study/snuba/snuba/datasets/storages/factory.py", line 72, in initialize_storage_factory
    _storage_factory()
  File "/Users/xwx/study/snuba/snuba/datasets/storages/factory.py", line 64, in _storage_factory
    _STORAGE_FACTORY = _StorageFactory()
                       ^^^^^^^^^^^^^^^^^
  File "/Users/xwx/study/snuba/snuba/datasets/storages/factory.py", line 23, in __init__
    self.__initialize()
  File "/Users/xwx/study/snuba/snuba/datasets/storages/factory.py", line 27, in __initialize
    storage = build_storage_from_config(config_file)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xwx/study/snuba/snuba/datasets/configuration/storage_builder.py", line 63, in build_storage_from_config
    storage_kwargs = {**storage_kwargs, **__build_writable_storage_kwargs(config)}
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xwx/study/snuba/snuba/datasets/configuration/storage_builder.py", line 103, in __build_writable_storage_kwargs
    STREAM_LOADER: build_stream_loader(config[STREAM_LOADER]),
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xwx/study/snuba/snuba/datasets/configuration/storage_builder.py", line 159, in build_stream_loader
    processor = DatasetMessageProcessor.from_name(processor_name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xwx/study/snuba/snuba/datasets/processors/__init__.py", line 30, in from_name
    return cast(Type["DatasetMessageProcessor"], cls.class_from_name(name))()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xwx/study/snuba/snuba/datasets/processors/metrics_bucket_processor.py", line 6, in __init__
    super().__init__("PolymorphicMetricsProcessor")
  File "/Users/xwx/study/snuba/snuba/datasets/processors/rust_compat_processor.py", line 20, in __init__
    self.__process_message = rust_snuba.process_message  # type: ignore
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'rust_snuba' has no attribute 'process_message'
```

it is same when run `snuba consumer`

**Comment by volokluev** [comment]
Run `make install-rs-dev`

**Comment by yujiaao** [comment]
> Run `make install-rs-dev`

```
:~/study/snuba|24.5.1⚡ ⇒  make install-rs-dev
/Users/xwx/.cargo/bin/cargo
. scripts/rust-envvars && cd rust_snuba/ && maturin develop
🔗 Found pyo3 bindings
🐍 Found CPython 3.12 at /Users/xwx/study/snuba/.venv/bin/python
📡 Using build options features from pyproject.toml
    Finished dev [unoptimized + debuginfo] target(s) in 0.57s
📦 Built wheel for CPython 3.12 to /var/folders/h0/6nx54wqd0fs_gwfpgwh_vp_40000gn/T/.tmpi5WjDS/rust_snuba-0.1.0-cp312-cp312-macosx_10_12_x86_64.whl
🛠 Installed rust_snuba-0.1.0
:~/study/snuba|24.5.1⚡ ⇒  snuba api
2024-09-05 13:28:10,320 Initializing Snuba...
['__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1651, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1698, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xwx/study/snuba/snuba/cli/__init__.py", line 58, in get_command
    initialize.initialize_snuba()
  File "/Users/xwx/study/snuba/snuba/core/initialize.py", line 41, in initialize_snuba
    _load_storages()
  File "/Users/xwx/study/snuba/snuba/core/initialize.py", line 23, in _load_storages
    initialize_storage_factory()
  File "/Users/xwx/study/snuba/snuba/datasets/storages/factory.py", line 72, in initialize_storage_factory
    _storage_factory()
  File "/Users/xwx/study/snuba/snuba/datasets/storages/factory.py", line 64, in _storage_factory
    _STORAGE_FACTORY = _StorageFactory()
                       ^^^^^^^^^^^^^^^^^
  File "/Users/xwx/study/snuba/snuba/datasets/storages/factory.py", line 23, in __init__
    self.__initialize()
  File "/Users/xwx/study/snuba/snuba/datasets/storages/factory.py", line 27, in __initialize
    storage = build_storage_from_config(config_file)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xwx/study/snuba/snuba/datasets/configuration/storage_builder.py", line 63, in build_storage_from_config
    storage_kwargs = {**storage_kwargs, **__build_writable_storage_kwargs(config)}
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xwx/study/snuba/snuba/datasets/configuration/storage_builder.py", line 103, in __build_writable_storage_kwargs
    STREAM_LOADER: build_stream_loader(config[STREAM_LOADER]),
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xwx/study/snuba/snuba/datasets/configuration/storage_builder.py", line 159, in build_stream_loader
    processor = DatasetMessageProcessor.from_name(processor_name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xwx/study/snuba/snuba/datasets/processors/__init__.py", line 30, in from_name
    return cast(Type["DatasetMessageProcessor"], cls.class_from_name(name))()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xwx/study/snuba/snuba/datasets/processors/metrics_bucket_processor.py", line 6, in __init__
    super().__init__("PolymorphicMetricsProcessor")
  File "/Users/xwx/study/snuba/snuba/datasets/processors/rust_compat_processor.py", line 22, in __init__
    self.__process_message = rust_snuba.process_message  # type: ignore
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'rust_snuba' has no attribute 'process_message'
```

seems after running make install-rs-dev the problem remains.

**Comment by yujiaao** [comment]
> [@yujiaao](https://github.com/yujiaao) let us know if the suggestion above works. Reopen the issue if it does not.

no helps
