### ISSUE TITLE
Snuba migration does not ran failing with inactive replicas error

### ISSUE THREAD

**Issue by rajeshhsejar444** [getsentry/snuba#6330]
I was getting error with Snuba pods in EKS cluster. Tried recreating the pods which does not help so planned to try it out migration commands. Pls find the error below

snuba migrations migrate
2024-09-20 12:03:21,269 Initializing Snuba...
2024-09-20 12:03:23,853 Snuba initialization took 2.5838967399977264s
{"module": "snuba.migrations.connect", "event": "Snuba has only been tested on Clickhouse versions up to 21.8 (sentry-clickhouse:9000 - 21.8.13.6). Higher versions might not be supported.", "severity": "warning", "timestamp": "2024-09-20T12:03:23.861145Z"}
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/migrations.py", line 87, in migrate
    check_for_inactive_replicas()
  File "/usr/src/snuba/snuba/migrations/connect.py", line 130, in check_for_inactive_replicas
    raise InactiveClickhouseReplica("\n".join(sorted(set(inactive_replica_info))))
snuba.migrations.errors.InactiveClickhouseReplica: Storage discover has inactive replicas for table groupassignee_local with 2 out of 3 replicas active.
Storage discover has inactive replicas for table groupedmessage_local with 2 out of 3 replicas active.
Storage errors has inactive replicas for table groupassignee_local with 2 out of 3 replicas active.
Storage errors has inactive replicas for table groupedmessage_local with 2 out of 3 replicas active.

Verified the total replicas for groupassignee_local which is 1. But still migrations commands fails with inactive replica error.

**Comment by onkar** [comment]
Thanks @davidtsuk for fixing this via https://github.com/getsentry/snuba/pull/6418.
