### ISSUE TITLE
Unable to run snuba migrations after `24.5.0`

### ISSUE THREAD

**Issue by waskow-consensys** [getsentry/snuba#6533]
### Environment

What version are you running? `24.5.0`

### Steps to Reproduce

1. Running `24.5.0`
2. Update to `24.5.1`

### Expected Result

Migration completes successfully....

### Actual Result

Migration fails
```
  containers:
  - command:
    - snuba
    - migrations
    - migrate
    - --force
```
Logs:
```bash
2024-11-07 19:21:46,370 Query: SELECT group, migration_id, status FROM migrations_dist FINAL WHERE group IN ('system', 'events', 'transactions', 'discover', 'outcomes', 'metrics', 'sessions', 'querylog', 'profiles', 'functions', 'replays', 'generic_metrics', 'test_migration', 'search_issues', 'spans', 'group_attributes', 'metrics_summaries', 'profile_chunks')
2024-11-07 19:21:46,370 Block "" send time: 0.000012
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/snuba/snuba/cli/migrations.py", line 114, in migrate
    runner.run_all(
  File "/usr/src/snuba/snuba/migrations/runner.py", line 178, in run_all
    pending_migrations = self._get_pending_migrations()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/snuba/snuba/migrations/runner.py", line 410, in _get_pending_migrations
    group_migrations = self._get_pending_migrations_for_group(group)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/snuba/snuba/migrations/runner.py", line 433, in _get_pending_migrations_for_group
    raise MigrationInProgress(str(migration_key))
snuba.migrations.errors.MigrationInProgress: profile_chunks: 0001_create_profile_chunks_table
```

So stuck at 24.5.0...

**Comment by evanh** [comment]
This error happens when a migration fails to run. Here you can see the migrations are stuck on `0001_create_profile_chunks_table`.

It's hard to debug this issue without knowing what the error with that migration was. My suggestion would be to either find the error with that migration in your logs, or you can run

`snuba migrations reverse-in-progress`

Which will reverse that migration, then you can run

`snuba migrations migrate -g profile_chunks`

If that migration fails, please post the error here and we will fix it.

**Comment by waskow-consensys** [comment]
Appreciate the response and the commands, I was able to get the migration rocking after using them.

Much appreciated!
