### ISSUE TITLE
dependency failed to start: container sentry-self-hosted-kafka-1 is unhealthy

### ISSUE THREAD

**Issue by Chrissi2812** [getsentry/snuba#6562]
### Environment

Sentry 23.11.0

### Steps to Reproduce

Upgrading from 23.11.0 -> 24.8.0

### Expected Result

Update succeeds

### Actual Result

Error Messages from install.sh 
```
▶ Bootstrapping and migrating Snuba ...
 Network sentry-self-hosted_default  Creating
 Network sentry-self-hosted_default  Created
 Container sentry-self-hosted-redis-1  Creating
 Container sentry-self-hosted-kafka-1  Creating
 Container sentry-self-hosted-clickhouse-1  Creating
 Container sentry-self-hosted-clickhouse-1  Created
 Container sentry-self-hosted-kafka-1  Created
 Container sentry-self-hosted-redis-1  Created
 Container sentry-self-hosted-redis-1  Starting
 Container sentry-self-hosted-clickhouse-1  Starting
 Container sentry-self-hosted-kafka-1  Starting
 Container sentry-self-hosted-redis-1  Started
 Container sentry-self-hosted-kafka-1  Started
 Container sentry-self-hosted-clickhouse-1  Started
dependency failed to start: container sentry-self-hosted-kafka-1 is unhealthy
Error in install/bootstrap-snuba.sh:3.
'$dcr snuba-api bootstrap --no-migrate --force' exited with status 1
-> ./install.sh:main:35
--> install/bootstrap-snuba.sh:source:3

Looks like you've already sent this error to us, we're on it :)
```

Kafka Logs
```
# docker compose --env-file .env logs kafka --since 10m
kafka-1  | ===> User
kafka-1  | uid=1000(appuser) gid=1000(appuser) groups=1000(appuser)
kafka-1  | ===> Configuring ...
kafka-1  | Running in KRaft mode...
kafka-1  | ===> Running preflight checks ...
kafka-1  | ===> Check if /var/lib/kafka/data is writable ...
kafka-1  | ===> Running in KRaft mode, skipping Zookeeper health check...
kafka-1  | ===> Using provided cluster id MkU3OEVBNTcwNTJENDM2Qk ...
kafka-1  | Log directory /var/lib/kafka/data is already formatted. Use --ignore-formatted to ignore this directory and format the others.
kafka-1  | ===> Launching ...
kafka-1  | ===> Launching kafka ...
kafka-1  | [2024-11-12 17:31:50,123] INFO Registered kafka:type=kafka.Log4jController MBean (kafka.utils.Log4jControllerRegistration$)
kafka-1  | [2024-11-12 17:31:50,673] ERROR Exiting Kafka due to fatal exception (kafka.Kafka$)
kafka-1  | kafka.common.InconsistentNodeIdException: Configured node.id `1001` doesn't match stored node.id `1389' in meta.properties. If you moved your data, make sure your configured controller.id matches. If you intend to create a new broker, you should remove all data in your data directories (log.dirs).
kafka-1  |      at kafka.server.KafkaRaftServer$.initializeLogDirs(KafkaRaftServer.scala:163)
kafka-1  |      at kafka.server.KafkaRaftServer.<init>(KafkaRaftServer.scala:57)
kafka-1  |      at kafka.Kafka$.buildServer(Kafka.scala:83)
kafka-1  |      at kafka.Kafka$.main(Kafka.scala:91)
kafka-1  |      at kafka.Kafka.main(Kafka.scala)
kafka-1  | ===> User
kafka-1  | uid=1000(appuser) gid=1000(appuser) groups=1000(appuser)
kafka-1  | ===> Configuring ...
kafka-1  | Running in KRaft mode...
kafka-1  | ===> Running preflight checks ...
kafka-1  | ===> Check if /var/lib/kafka/data is writable ...
kafka-1  | ===> Running in KRaft mode, skipping Zookeeper health check...
kafka-1  | ===> Using provided cluster id MkU3OEVBNTcwNTJENDM2Qk ...
kafka-1  | Log directory /var/lib/kafka/data is already formatted. Use --ignore-formatted to ignore this directory and format the others.
kafka-1  | ===> Launching ...
kafka-1  | ===> Launching kafka ...
kafka-1  | [2024-11-12 17:31:59,345] INFO Registered kafka:type=kafka.Log4jController MBean (kafka.utils.Log4jControllerRegistration$)
kafka-1  | [2024-11-12 17:31:59,908] ERROR Exiting Kafka due to fatal exception (kafka.Kafka$)
kafka-1  | kafka.common.InconsistentNodeIdException: Configured node.id `1001` doesn't match stored node.id `1389' in meta.properties. If you moved your data, make sure your configured controller.id matches. If you intend to create a new broker, you should remove all data in your data directories (log.dirs).
kafka-1  |      at kafka.server.KafkaRaftServer$.initializeLogDirs(KafkaRaftServer.scala:163)
kafka-1  |      at kafka.server.KafkaRaftServer.<init>(KafkaRaftServer.scala:57)
kafka-1  |      at kafka.Kafka$.buildServer(Kafka.scala:83)
kafka-1  |      at kafka.Kafka$.main(Kafka.scala:91)
kafka-1  |      at kafka.Kafka.main(Kafka.scala)
kafka-1  | ===> User
kafka-1  | uid=1000(appuser) gid=1000(appuser) groups=1000(appuser)
kafka-1  | ===> Configuring ...
kafka-1  | Running in KRaft mode...
kafka-1  | ===> Running preflight checks ...
kafka-1  | ===> Check if /var/lib/kafka/data is writable ...
kafka-1  | ===> Running in KRaft mode, skipping Zookeeper health check...
kafka-1  | ===> Using provided cluster id MkU3OEVBNTcwNTJENDM2Qk ...
kafka-1  | Log directory /var/lib/kafka/data is already formatted. Use --ignore-formatted to ignore this directory and format the others.
kafka-1  | ===> Launching ...
kafka-1  | ===> Launching kafka ...
kafka-1  | [2024-11-12 17:32:08,659] INFO Registered kafka:type=kafka.Log4jController MBean (kafka.utils.Log4jControllerRegistration$)
kafka-1  | [2024-11-12 17:32:09,222] ERROR Exiting Kafka due to fatal exception (kafka.Kafka$)
kafka-1  | kafka.common.InconsistentNodeIdException: Configured node.id `1001` doesn't match stored node.id `1389' in meta.properties. If you moved your data, make sure your configured controller.id matches. If you intend to create a new broker, you should remove all data in your data directories (log.dirs).
kafka-1  |      at kafka.server.KafkaRaftServer$.initializeLogDirs(KafkaRaftServer.scala:163)
kafka-1  |      at kafka.server.KafkaRaftServer.<init>(KafkaRaftServer.scala:57)
kafka-1  |      at kafka.Kafka$.buildServer(Kafka.scala:83)
kafka-1  |      at kafka.Kafka$.main(Kafka.scala:91)
kafka-1  |      at kafka.Kafka.main(Kafka.scala)
kafka-1  | ===> User
kafka-1  | uid=1000(appuser) gid=1000(appuser) groups=1000(appuser)
kafka-1  | ===> Configuring ...
kafka-1  | Running in KRaft mode...
kafka-1  | ===> Running preflight checks ...
kafka-1  | ===> Check if /var/lib/kafka/data is writable ...
kafka-1  | ===> Running in KRaft mode, skipping Zookeeper health check...
kafka-1  | ===> Using provided cluster id MkU3OEVBNTcwNTJENDM2Qk ...
kafka-1  | Log directory /var/lib/kafka/data is already formatted. Use --ignore-formatted to ignore this directory and format the others.
kafka-1  | ===> Launching ...
kafka-1  | ===> Launching kafka ...
kafka-1  | [2024-11-12 17:32:17,749] INFO Registered kafka:type=kafka.Log4jController MBean (kafka.utils.Log4jControllerRegistration$)
kafka-1  | [2024-11-12 17:32:18,344] ERROR Exiting Kafka due to fatal exception (kafka.Kafka$)
kafka-1  | kafka.common.InconsistentNodeIdException: Configured node.id `1001` doesn't match stored node.id `1389' in meta.properties. If you moved your data, make sure your configured controller.id matches. If you intend to create a new broker, you should remove all data in your data directories (log.dirs).
kafka-1  |      at kafka.server.KafkaRaftServer$.initializeLogDirs(KafkaRaftServer.scala:163)
kafka-1  |      at kafka.server.KafkaRaftServer.<init>(KafkaRaftServer.scala:57)
kafka-1  |      at kafka.Kafka$.buildServer(Kafka.scala:83)
kafka-1  |      at kafka.Kafka$.main(Kafka.scala:91)
kafka-1  |      at kafka.Kafka.main(Kafka.scala)
kafka-1  | ===> User
kafka-1  | uid=1000(appuser) gid=1000(appuser) groups=1000(appuser)
kafka-1  | ===> Configuring ...
kafka-1  | Running in KRaft mode...
kafka-1  | ===> Running preflight checks ...
kafka-1  | ===> Check if /var/lib/kafka/data is writable ...
kafka-1  | ===> Running in KRaft mode, skipping Zookeeper health check...
kafka-1  | ===> Using provided cluster id MkU3OEVBNTcwNTJENDM2Qk ...
kafka-1  | Log directory /var/lib/kafka/data is already formatted. Use --ignore-formatted to ignore this directory and format the others.
kafka-1  | ===> Launching ...
kafka-1  | ===> Launching kafka ...
kafka-1  | [2024-11-12 17:32:27,095] INFO Registered kafka:type=kafka.Log4jController MBean (kafka.utils.Log4jControllerRegistration$)
kafka-1  | [2024-11-12 17:32:27,654] ERROR Exiting Kafka due to fatal exception (kafka.Kafka$)
kafka-1  | kafka.common.InconsistentNodeIdException: Configured node.id `1001` doesn't match stored node.id `1389' in meta.properties. If you moved your data, make sure your configured controller.id matches. If you intend to create a new broker, you should remove all data in your data directories (log.dirs).
kafka-1  |      at kafka.server.KafkaRaftServer$.initializeLogDirs(KafkaRaftServer.scala:163)
kafka-1  |      at kafka.server.KafkaRaftServer.<init>(KafkaRaftServer.scala:57)
kafka-1  |      at kafka.Kafka$.buildServer(Kafka.scala:83)
kafka-1  |      at kafka.Kafka$.main(Kafka.scala:91)
kafka-1  |      at kafka.Kafka.main(Kafka.scala)
kafka-1  | ===> User
kafka-1  | uid=1000(appuser) gid=1000(appuser) groups=1000(appuser)
kafka-1  | ===> Configuring ...
kafka-1  | Running in KRaft mode...
kafka-1  | ===> Running preflight checks ...
kafka-1  | ===> Check if /var/lib/kafka/data is writable ...
kafka-1  | ===> Running in KRaft mode, skipping Zookeeper health check...
kafka-1  | ===> Using provided cluster id MkU3OEVBNTcwNTJENDM2Qk ...
kafka-1  | Log directory /var/lib/kafka/data is already formatted. Use --ignore-formatted to ignore this directory and format the others.
kafka-1  | ===> Launching ...
kafka-1  | ===> Launching kafka ...
kafka-1  | [2024-11-12 17:32:37,299] INFO Registered kafka:type=kafka.Log4jController MBean (kafka.utils.Log4jControllerRegistration$)
kafka-1  | [2024-11-12 17:32:37,856] ERROR Exiting Kafka due to fatal exception (kafka.Kafka$)
kafka-1  | kafka.common.InconsistentNodeIdException: Configured node.id `1001` doesn't match stored node.id `1389' in meta.properties. If you moved your data, make sure your configured controller.id matches. If you intend to create a new broker, you should remove all data in your data directories (log.dirs).
kafka-1  |      at kafka.server.KafkaRaftServer$.initializeLogDirs(KafkaRaftServer.scala:163)
kafka-1  |      at kafka.server.KafkaRaftServer.<init>(KafkaRaftServer.scala:57)
kafka-1  |      at kafka.Kafka$.buildServer(Kafka.scala:83)
kafka-1  |      at kafka.Kafka$.main(Kafka.scala:91)
kafka-1  |      at kafka.Kafka.main(Kafka.scala)
kafka-1  | ===> User
kafka-1  | uid=1000(appuser) gid=1000(appuser) groups=1000(appuser)
kafka-1  | ===> Configuring ...
kafka-1  | Running in KRaft mode...
kafka-1  | ===> Running preflight checks ...
kafka-1  | ===> Check if /var/lib/kafka/data is writable ...
kafka-1  | ===> Running in KRaft mode, skipping Zookeeper health check...
kafka-1  | ===> Using provided cluster id MkU3OEVBNTcwNTJENDM2Qk ...
kafka-1  | Log directory /var/lib/kafka/data is already formatted. Use --ignore-formatted to ignore this directory and format the others.
kafka-1  | ===> Launching ...
kafka-1  | ===> Launching kafka ...
kafka-1  | [2024-11-12 17:32:49,209] INFO Registered kafka:type=kafka.Log4jController MBean (kafka.utils.Log4jControllerRegistration$)
kafka-1  | [2024-11-12 17:32:49,809] ERROR Exiting Kafka due to fatal exception (kafka.Kafka$)
kafka-1  | kafka.common.InconsistentNodeIdException: Configured node.id `1001` doesn't match stored node.id `1389' in meta.properties. If you moved your data, make sure your configured controller.id matches. If you intend to create a new broker, you should remove all data in your data directories (log.dirs).
kafka-1  |      at kafka.server.KafkaRaftServer$.initializeLogDirs(KafkaRaftServer.scala:163)
kafka-1  |      at kafka.server.KafkaRaftServer.<init>(KafkaRaftServer.scala:57)
kafka-1  |      at kafka.Kafka$.buildServer(Kafka.scala:83)
kafka-1  |      at kafka.Kafka$.main(Kafka.scala:91)
kafka-1  |      at kafka.Kafka.main(Kafka.scala)
kafka-1  | ===> User
kafka-1  | uid=1000(appuser) gid=1000(appuser) groups=1000(appuser)
kafka-1  | ===> Configuring ...
kafka-1  | Running in KRaft mode...
kafka-1  | ===> Running preflight checks ...
kafka-1  | ===> Check if /var/lib/kafka/data is writable ...
kafka-1  | ===> Running in KRaft mode, skipping Zookeeper health check...
kafka-1  | ===> Using provided cluster id MkU3OEVBNTcwNTJENDM2Qk ...
kafka-1  | Log directory /var/lib/kafka/data is already formatted. Use --ignore-formatted to ignore this directory and format the others.
kafka-1  | ===> Launching ...
kafka-1  | ===> Launching kafka ...
kafka-1  | [2024-11-12 17:33:04,206] INFO Registered kafka:type=kafka.Log4jController MBean (kafka.utils.Log4jControllerRegistration$)
```

**Comment by Chrissi2812** [comment]
Okay submitted it to the wrong repo should have been self-hosted. 
Also I got this fixed with the nuclear option. Without loosing to much data. Most older events still there.
