### ISSUE TITLE
TypeError: getattr(): attribute name must be string

### ISSUE THREAD

**Issue by amoskyler** [getsentry/snuba#766]
I am running sentry onpremise and am seeing this stack trace coming from the `snuba-cleanup` process
```snuba-cleanup_1           | Traceback (most recent call last):
snuba-cleanup_1           |   File "/usr/local/bin/snuba", line 11, in <module>
snuba-cleanup_1           |     load_entry_point('snuba', 'console_scripts', 'snuba')()
snuba-cleanup_1           |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 722, in __call__
snuba-cleanup_1           |     return self.main(*args, **kwargs)
snuba-cleanup_1           |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 697, in main
snuba-cleanup_1           |     rv = self.invoke(ctx)
snuba-cleanup_1           |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
snuba-cleanup_1           |     return _process_result(sub_ctx.command.invoke(sub_ctx))
snuba-cleanup_1           |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 895, in invoke
snuba-cleanup_1           |     return ctx.invoke(self.callback, **ctx.params)
snuba-cleanup_1           |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 535, in invoke
snuba-cleanup_1           |     return callback(*args, **kwargs)
snuba-cleanup_1           |   File "/usr/src/snuba/snuba/cli/cleanup.py", line 50, in cleanup
snuba-cleanup_1           |     setup_logging(log_level)
snuba-cleanup_1           |   File "/usr/src/snuba/snuba/environment.py", line 16, in setup_logging
snuba-cleanup_1           |     level=getattr(logging, level, settings.LOG_LEVEL).upper(),
snuba-cleanup_1           | TypeError: getattr(): attribute name must be string
```

I can't tell if this is a configuration error with how sentry onpremise is configured or a lower level issue with snuba iteslf.

**Comment by tkaemming** [comment]
This was fixed with #748, please update your docker image.
