### ISSUE TITLE
cimpl.KafkaException: KafkaError{code=CLUSTER_AUTHORIZATION_FAILED

### ISSUE THREAD

**Issue by caiqing0204** [getsentry/snuba#995]
Hello, When I used snuba, I made a mistake, and I want to trouble you guys to see that my Kafka cluster does not need authentication.

`
2020-06-04 14:23:39,309 Failed to create topic snuba-commit-log
Traceback (most recent call last):
  File "/home/maintain/workspaces/snuba/lib/python3.7/site-packages/snuba-0.0.0-py3.7.egg/snuba/cli/bootstrap.py", line 93, in bootstrap
    future.result()
  File "/usr/local/python3/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/local/python3/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
cimpl.KafkaException: KafkaError{code=CLUSTER_AUTHORIZATION_FAILED,val=31,str="Broker: Cluster authorization failed"}
2020-06-04 14:23:39,309 Failed to create topic outcomes
Traceback (most recent call last):
  File "/home/maintain/workspaces/snuba/lib/python3.7/site-packages/snuba-0.0.0-py3.7.egg/snuba/cli/bootstrap.py", line 93, in bootstrap
    future.result()
  File "/usr/local/python3/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/local/python3/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
cimpl.KafkaException: KafkaError{code=CLUSTER_AUTHORIZATION_FAILED,val=31,str="Broker: Cluster authorization failed"}
`

**Comment by fpacifici** [comment]
Hi, thanks for reaching out,
Could you please verify that your kafka cluster does not have an acl or an authorizer configured?

```
kafka-acls --bootstrap-server YOURCLUSTER --list
```
ran from anywhere you have access to your cluster

and could you also confirm there is non authorization required by trying to create a topic from a different host than your broker?

```
 kafka-topics --create --zookeeper YOUR_ZOOKEEPER_SERV --replication-factor 1 --partitions 1 --topic test2
```
if you deployed kafka during sentry installation following https://github.com/getsentry/onpremise YOUR_ZOOKEEPER_SERV is likely to be sentry_zookeeper:2181

This should confirm whether your kafka cluster is allowing topic creation without authorization, which seems the problem from your error message.

Thanks you

**Comment by caiqing0204** [comment]
ok, thanks!
